# Generated by Django 5.2.7 on 2025-10-17 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project_app", "0004_alter_project_collaborators"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of your research background",
                        max_length=500,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Your current location (e.g., 'Tokyo, Japan')",
                        max_length=200,
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True, help_text="Your current institution", max_length=200
                    ),
                ),
                (
                    "research_interests",
                    models.TextField(
                        blank=True,
                        help_text="Your research areas and interests",
                        max_length=500,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Your personal or professional website"
                    ),
                ),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        help_text="Your ORCID identifier (e.g., 0000-0000-0000-0000)",
                        max_length=19,
                    ),
                ),
                (
                    "academic_title",
                    models.CharField(
                        blank=True,
                        help_text="Your academic title (e.g., PhD, Professor)",
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Your department or faculty",
                        max_length=200,
                    ),
                ),
                (
                    "google_scholar",
                    models.URLField(
                        blank=True, help_text="Your Google Scholar profile"
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, help_text="Your LinkedIn profile"),
                ),
                (
                    "researchgate",
                    models.URLField(blank=True, help_text="Your ResearchGate profile"),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True,
                        help_text="Your Twitter handle (without @)",
                        max_length=50,
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("restricted", "Restricted"),
                            ("private", "Private"),
                        ],
                        default="public",
                        help_text="Who can view your profile",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, help_text="Make profile public"),
                ),
                (
                    "show_email",
                    models.BooleanField(
                        default=False, help_text="Show email in public profile"
                    ),
                ),
                (
                    "allow_collaboration",
                    models.BooleanField(
                        default=True, help_text="Allow collaboration requests"
                    ),
                ),
                (
                    "allow_messages",
                    models.BooleanField(
                        default=True, help_text="Allow messages from other users"
                    ),
                ),
                (
                    "is_academic_ja",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically detected: User belongs to Japanese academic institution",
                    ),
                ),
                (
                    "deletion_scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When account deletion was scheduled",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_active_repository",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last repository the user was working on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_active_for_users",
                        to="project_app.project",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_app_userprofile",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
    ]
