# Generated by Django 5.2.7 on 2025-10-18 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ssh_key_created_at",
            field=models.DateTimeField(
                blank=True, help_text="When SSH key was generated", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ssh_key_fingerprint",
            field=models.CharField(
                blank=True, help_text="SSH key fingerprint (SHA256)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ssh_key_last_used_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time SSH key was used", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ssh_public_key",
            field=models.TextField(
                blank=True, help_text="User's SSH public key for Git operations"
            ),
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this API key", max_length=100
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="First 8 characters of the key (for display)",
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="SHA256 hash of the full key",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        default=list, help_text="List of allowed scopes/permissions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this key expires (optional)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profile_app_apikey",
                "ordering": ["-created_at"],
            },
        ),
    ]
