# Generated by Django 5.2.7 on 2025-10-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0002_userprofile_ssh_key_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bitbucket_token",
            field=models.CharField(
                blank=True,
                help_text="Bitbucket App Password for importing private repos",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_token",
            field=models.CharField(
                blank=True,
                help_text="GitHub Personal Access Token for importing private repos",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gitlab_token",
            field=models.CharField(
                blank=True,
                help_text="GitLab Personal Access Token for importing private repos",
                max_length=255,
            ),
        ),
    ]
