# Generated by Django 5.2.7 on 2025-10-22 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0005_userprofile_timezone"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userprofile",
            table="core_app_userprofile",
        ),
    ]
