# Generated by Django 5.2.7 on 2025-11-14 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0006_alter_userprofile_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceSSHKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Descriptive name for this key (e.g., 'Work Laptop', 'Home PC')",
                        max_length=100,
                    ),
                ),
                ("public_key", models.TextField(help_text="SSH public key content")),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="SSH key fingerprint (SHA256)", max_length=100
                    ),
                ),
                (
                    "key_type",
                    models.CharField(
                        default="rsa",
                        help_text="Key algorithm (rsa, ed25519, ecdsa, etc.)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this key was used for authentication",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_ssh_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_app_workspacesshkey",
                "ordering": ["-created_at"],
                "unique_together": {("user", "fingerprint")},
            },
        ),
    ]
