# Generated by Django 4.2.11 on 2025-06-29 13:36

import apps.reference_sync_app.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholar_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceManagerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('mendeley', 'Mendeley'), ('zotero', 'Zotero')], max_length=20)),
                ('account_name', models.CharField(help_text='Display name for the account', max_length=200)),
                ('access_token', apps.reference_sync_app.models.EncryptedTextField(blank=True, help_text='OAuth access token')),
                ('refresh_token', apps.reference_sync_app.models.EncryptedTextField(blank=True, help_text='OAuth refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('external_user_id', models.CharField(blank=True, help_text='User ID from the service', max_length=100)),
                ('account_email', models.EmailField(blank=True, help_text='Email associated with the account', max_length=254)),
                ('account_metadata', models.JSONField(blank=True, default=dict, help_text='Additional account info')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_count', models.IntegerField(default=0)),
                ('api_calls_today', models.IntegerField(default=0)),
                ('api_quota_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('mendeley', 'Mendeley'), ('zotero', 'Zotero')], max_length=20)),
                ('external_id', models.CharField(help_text='ID in the external service', max_length=200)),
                ('external_group_id', models.CharField(blank=True, help_text='Group/collection ID', max_length=200)),
                ('local_hash', models.CharField(blank=True, help_text='Hash of local data for change detection', max_length=64)),
                ('remote_hash', models.CharField(blank=True, help_text='Hash of remote data', max_length=64)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('local_newer', 'Local Newer'), ('remote_newer', 'Remote Newer'), ('conflict', 'Conflict'), ('error', 'Error')], default='synced', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='reference_sync_app.referencemanageraccount')),
                ('local_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_mappings', to='scholar_app.searchindex')),
            ],
        ),
        migrations.CreateModel(
            name='SyncProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name for this sync profile', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of sync settings')),
                ('auto_sync', models.BooleanField(default=False, help_text='Enable automatic syncing')),
                ('sync_frequency', models.CharField(choices=[('manual', 'Manual Only'), ('hourly', 'Every Hour'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Disabled')], default='manual', max_length=20)),
                ('sync_direction', models.CharField(choices=[('bidirectional', 'Bidirectional'), ('import_only', 'Import Only'), ('export_only', 'Export Only')], default='bidirectional', max_length=20)),
                ('conflict_resolution', models.CharField(choices=[('ask', 'Ask User'), ('local_wins', 'Local Wins'), ('remote_wins', 'Remote Wins'), ('merge', 'Try to Merge'), ('skip', 'Skip Conflicts')], default='ask', max_length=20)),
                ('sync_collections', models.JSONField(blank=True, default=list, help_text='Specific collections to sync (empty = all)')),
                ('sync_tags', models.JSONField(blank=True, default=list, help_text='Only sync items with these tags')),
                ('exclude_tags', models.JSONField(blank=True, default=list, help_text='Exclude items with these tags')),
                ('sync_pdfs', models.BooleanField(default=True, help_text='Sync PDF files')),
                ('sync_notes', models.BooleanField(default=True, help_text='Sync notes and annotations')),
                ('sync_attachments', models.BooleanField(default=False, help_text='Sync other attachments')),
                ('sync_after_date', models.DateField(blank=True, help_text='Only sync items after this date', null=True)),
                ('sync_before_date', models.DateField(blank=True, help_text='Only sync items before this date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('next_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(related_name='sync_profiles', to='reference_sync_app.referencemanageraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('webhook', 'Webhook'), ('startup', 'Application Startup')], default='manual', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_created', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('items_deleted', models.IntegerField(default=0)),
                ('items_skipped', models.IntegerField(default=0)),
                ('conflicts_found', models.IntegerField(default=0)),
                ('conflicts_resolved', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('api_calls_made', models.IntegerField(default=0)),
                ('data_transferred_mb', models.FloatField(default=0.0)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_sessions', to='reference_sync_app.syncprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('operation', models.CharField(choices=[('auth', 'Authentication'), ('fetch', 'Fetch Data'), ('create', 'Create Item'), ('update', 'Update Item'), ('delete', 'Delete Item'), ('conflict', 'Conflict Resolution'), ('error', 'Error Handling'), ('cleanup', 'Cleanup')], max_length=20)),
                ('message', models.TextField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_sync_app.referencemapping')),
                ('sync_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reference_sync_app.syncsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflictResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('title', 'Title Mismatch'), ('authors', 'Authors Mismatch'), ('publication_date', 'Publication Date Mismatch'), ('abstract', 'Abstract Mismatch'), ('keywords', 'Keywords Mismatch'), ('notes', 'Notes Conflict'), ('tags', 'Tags Conflict'), ('pdf', 'PDF File Conflict'), ('metadata', 'Metadata Conflict'), ('deleted', 'Deletion Conflict')], max_length=30)),
                ('local_value', models.JSONField(help_text='Local version of the conflicted data')),
                ('remote_value', models.JSONField(help_text='Remote version of the conflicted data')),
                ('resolution', models.CharField(blank=True, choices=[('local_wins', 'Local Version Kept'), ('remote_wins', 'Remote Version Kept'), ('merged', 'Merged Both Versions'), ('manual', 'Manually Resolved'), ('skipped', 'Skipped/Ignored')], max_length=20)),
                ('resolved_value', models.JSONField(blank=True, help_text='Final resolved value', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about the resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reference_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='reference_sync_app.referencemapping')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sync_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='reference_sync_app.syncsession')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('mendeley', 'Mendeley'), ('zotero', 'Zotero')], max_length=20)),
                ('webhook_url', models.URLField(help_text='URL for the webhook endpoint')),
                ('secret_key', models.CharField(help_text='Secret key for webhook verification', max_length=100)),
                ('events', models.JSONField(default=list, help_text='List of events to trigger sync on')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='reference_sync_app.referencemanageraccount')),
            ],
            options={
                'indexes': [models.Index(fields=['service', 'is_active'], name='reference_s_service_941a9d_idx')],
                'unique_together': {('account', 'service')},
            },
        ),
        migrations.CreateModel(
            name='SyncStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sync_sessions', models.IntegerField(default=0)),
                ('successful_syncs', models.IntegerField(default=0)),
                ('failed_syncs', models.IntegerField(default=0)),
                ('items_synced', models.IntegerField(default=0)),
                ('items_created', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('items_deleted', models.IntegerField(default=0)),
                ('conflicts_found', models.IntegerField(default=0)),
                ('conflicts_resolved', models.IntegerField(default=0)),
                ('total_sync_time', models.DurationField(default=datetime.timedelta)),
                ('api_calls_made', models.IntegerField(default=0)),
                ('data_transferred_mb', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='reference_s_user_id_f0bc08_idx'), models.Index(fields=['date'], name='reference_s_date_944b2b_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='syncsession',
            index=models.Index(fields=['profile', '-started_at'], name='reference_s_profile_e105e1_idx'),
        ),
        migrations.AddIndex(
            model_name='syncsession',
            index=models.Index(fields=['status', '-started_at'], name='reference_s_status_227ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='syncprofile',
            index=models.Index(fields=['user', 'is_active'], name='reference_s_user_id_eb2211_idx'),
        ),
        migrations.AddIndex(
            model_name='syncprofile',
            index=models.Index(fields=['auto_sync', 'next_sync'], name='reference_s_auto_sy_52671c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncprofile',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['sync_session', '-created_at'], name='reference_s_sync_se_8455a3_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['level', '-created_at'], name='reference_s_level_cd9ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='referencemapping',
            index=models.Index(fields=['local_paper', 'service'], name='reference_s_local_p_53217f_idx'),
        ),
        migrations.AddIndex(
            model_name='referencemapping',
            index=models.Index(fields=['service', 'external_id'], name='reference_s_service_8bf592_idx'),
        ),
        migrations.AddIndex(
            model_name='referencemapping',
            index=models.Index(fields=['sync_status'], name='reference_s_sync_st_65b786_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referencemapping',
            unique_together={('service', 'external_id', 'account')},
        ),
        migrations.AddIndex(
            model_name='referencemanageraccount',
            index=models.Index(fields=['user', 'service'], name='reference_s_user_id_888f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='referencemanageraccount',
            index=models.Index(fields=['status', 'is_active'], name='reference_s_status_88c581_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referencemanageraccount',
            unique_together={('user', 'service', 'external_user_id')},
        ),
        migrations.AddIndex(
            model_name='conflictresolution',
            index=models.Index(fields=['sync_session', 'conflict_type'], name='reference_s_sync_se_9d28e4_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictresolution',
            index=models.Index(fields=['reference_mapping', '-created_at'], name='reference_s_referen_aedf30_idx'),
        ),
    ]
