# Generated by Django 4.2.11 on 2025-06-29 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholar_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcidProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orcid_id', models.CharField(help_text='ORCID iD (e.g., 0000-0000-0000-0000)', max_length=19, unique=True)),
                ('given_name', models.CharField(blank=True, max_length=255)),
                ('family_name', models.CharField(blank=True, max_length=255)),
                ('credit_name', models.CharField(blank=True, help_text='Published/Credit name', max_length=255)),
                ('biography', models.TextField(blank=True)),
                ('researcher_urls', models.JSONField(blank=True, default=list, help_text='List of researcher URLs')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Research keywords')),
                ('current_affiliation', models.CharField(blank=True, max_length=500)),
                ('affiliations', models.JSONField(blank=True, default=list, help_text='List of all affiliations')),
                ('is_synced', models.BooleanField(default=False, help_text='Profile has been synced with ORCID')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_publications', models.BooleanField(default=True, help_text='Auto-sync publications from ORCID')),
                ('auto_sync_enabled', models.BooleanField(default=True, help_text='Enable automatic periodic sync')),
                ('public_profile', models.BooleanField(default=True, help_text='Make ORCID profile visible to other users')),
                ('show_publications', models.BooleanField(default=True, help_text='Show ORCID publications in Scholar')),
                ('orcid_record', models.JSONField(blank=True, default=dict, help_text='Raw ORCID record data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcid_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ORCID Profile',
                'verbose_name_plural': 'ORCID Profiles',
                'ordering': ['family_name', 'given_name'],
            },
        ),
        migrations.CreateModel(
            name='OrcidOAuth2Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='ORCID access token', max_length=255)),
                ('refresh_token', models.CharField(blank=True, help_text='ORCID refresh token', max_length=255)),
                ('token_type', models.CharField(default='bearer', max_length=50)),
                ('scope', models.CharField(help_text='OAuth scope granted', max_length=255)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('orcid_id', models.CharField(help_text='ORCID iD (e.g., 0000-0000-0000-0000)', max_length=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcid_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ORCID OAuth2 Token',
                'verbose_name_plural': 'ORCID OAuth2 Tokens',
            },
        ),
        migrations.CreateModel(
            name='OrcidWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(help_text='Work title')),
                ('work_type', models.CharField(choices=[('artistic-performance', 'Artistic Performance'), ('book-chapter', 'Book Chapter'), ('book-review', 'Book Review'), ('book', 'Book'), ('conference-abstract', 'Conference Abstract'), ('conference-paper', 'Conference Paper'), ('conference-poster', 'Conference Poster'), ('data-set', 'Dataset'), ('dictionary-entry', 'Dictionary Entry'), ('disclosure', 'Disclosure'), ('dissertation', 'Dissertation'), ('edited-book', 'Edited Book'), ('encyclopedia-entry', 'Encyclopedia Entry'), ('invention', 'Invention'), ('journal-article', 'Journal Article'), ('journal-issue', 'Journal Issue'), ('lecture-speech', 'Lecture/Speech'), ('license', 'License'), ('magazine-article', 'Magazine Article'), ('manual', 'Manual'), ('newsletter-article', 'Newsletter Article'), ('newspaper-article', 'Newspaper Article'), ('online-resource', 'Online Resource'), ('other', 'Other'), ('patent', 'Patent'), ('registered-copyright', 'Registered Copyright'), ('report', 'Report'), ('research-technique', 'Research Technique'), ('research-tool', 'Research Tool'), ('spin-off-company', 'Spin-off Company'), ('standards-and-policy', 'Standards and Policy'), ('supervised-student-publication', 'Supervised Student Publication'), ('technical-standard', 'Technical Standard'), ('test', 'Test'), ('trademark', 'Trademark'), ('translation', 'Translation'), ('website', 'Website'), ('working-paper', 'Working Paper')], max_length=50)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('journal_title', models.CharField(blank=True, max_length=500)),
                ('short_description', models.TextField(blank=True)),
                ('external_ids', models.JSONField(blank=True, default=list, help_text='External identifiers (DOI, etc.)')),
                ('url', models.URLField(blank=True)),
                ('put_code', models.CharField(help_text='ORCID put-code', max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Raw ORCID work data')),
                ('is_imported', models.BooleanField(default=False, help_text='Imported to relevant SciTeX module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcid_works', to='orcid_app.orcidprofile')),
            ],
            options={
                'verbose_name': 'ORCID Work',
                'verbose_name_plural': 'ORCID Works',
                'ordering': ['-publication_date', '-created_at'],
                'indexes': [models.Index(fields=['profile', '-publication_date'], name='orcid_app_o_profile_c731a2_idx'), models.Index(fields=['work_type'], name='orcid_app_o_work_ty_38a3b1_idx'), models.Index(fields=['is_imported'], name='orcid_app_o_is_impo_82e300_idx')],
                'unique_together': {('profile', 'put_code')},
            },
        ),
        migrations.CreateModel(
            name='OrcidSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('profile', 'Profile Sync'), ('publications', 'Publications Sync'), ('works', 'Works Sync'), ('full', 'Full Sync')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_created', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('items_skipped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='orcid_app.orcidprofile')),
            ],
            options={
                'verbose_name': 'ORCID Sync Log',
                'verbose_name_plural': 'ORCID Sync Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['profile', '-started_at'], name='orcid_app_o_profile_1c0f98_idx'), models.Index(fields=['status'], name='orcid_app_o_status_299b5f_idx'), models.Index(fields=['sync_type'], name='orcid_app_o_sync_ty_2cd4cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrcidPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(help_text='Publication title')),
                ('publication_type', models.CharField(choices=[('journal-article', 'Journal Article'), ('book', 'Book'), ('book-chapter', 'Book Chapter'), ('book-review', 'Book Review'), ('conference-paper', 'Conference Paper'), ('conference-abstract', 'Conference Abstract'), ('conference-poster', 'Conference Poster'), ('dissertation', 'Dissertation'), ('edited-book', 'Edited Book'), ('encyclopedia-entry', 'Encyclopedia Entry'), ('magazine-article', 'Magazine Article'), ('manual', 'Manual'), ('newsletter-article', 'Newsletter Article'), ('newspaper-article', 'Newspaper Article'), ('online-resource', 'Online Resource'), ('other', 'Other'), ('patent', 'Patent'), ('registered-copyright', 'Registered Copyright'), ('report', 'Report'), ('research-tool', 'Research Tool'), ('supervised-student-publication', 'Supervised Student Publication'), ('test', 'Test'), ('translation', 'Translation'), ('website', 'Website'), ('working-paper', 'Working Paper')], default='journal-article', max_length=50)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, help_text='Full publication date if available', null=True)),
                ('journal', models.CharField(blank=True, help_text='Journal or venue name', max_length=500)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=100)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=255)),
                ('pmid', models.CharField(blank=True, help_text='PubMed ID', max_length=20)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('issn', models.CharField(blank=True, max_length=9)),
                ('url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('authors', models.JSONField(blank=True, default=list, help_text='List of authors')),
                ('orcid_put_code', models.CharField(help_text='ORCID put-code for this work', max_length=50)),
                ('orcid_raw_data', models.JSONField(blank=True, default=dict, help_text='Raw ORCID API response')),
                ('is_imported', models.BooleanField(default=False, help_text='Imported into Scholar module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcid_publications', to='orcid_app.orcidprofile')),
                ('scholar_paper', models.ForeignKey(blank=True, help_text='Linked Scholar paper', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcid_publications', to='scholar_app.searchindex')),
            ],
            options={
                'verbose_name': 'ORCID Publication',
                'verbose_name_plural': 'ORCID Publications',
                'ordering': ['-publication_year', '-created_at'],
                'indexes': [models.Index(fields=['profile', '-publication_year'], name='orcid_app_o_profile_f14bc0_idx'), models.Index(fields=['doi'], name='orcid_app_o_doi_d7595f_idx'), models.Index(fields=['pmid'], name='orcid_app_o_pmid_442cea_idx'), models.Index(fields=['publication_type'], name='orcid_app_o_publica_4c5a8d_idx'), models.Index(fields=['is_imported'], name='orcid_app_o_is_impo_943425_idx')],
                'unique_together': {('profile', 'orcid_put_code')},
            },
        ),
        migrations.AddIndex(
            model_name='orcidprofile',
            index=models.Index(fields=['orcid_id'], name='orcid_app_o_orcid_i_754d19_idx'),
        ),
        migrations.AddIndex(
            model_name='orcidprofile',
            index=models.Index(fields=['user'], name='orcid_app_o_user_id_66620a_idx'),
        ),
        migrations.AddIndex(
            model_name='orcidprofile',
            index=models.Index(fields=['last_sync_at'], name='orcid_app_o_last_sy_827bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='orcidoauth2token',
            index=models.Index(fields=['user'], name='orcid_app_o_user_id_bcbfa4_idx'),
        ),
        migrations.AddIndex(
            model_name='orcidoauth2token',
            index=models.Index(fields=['orcid_id'], name='orcid_app_o_orcid_i_493d87_idx'),
        ),
        migrations.AddIndex(
            model_name='orcidoauth2token',
            index=models.Index(fields=['expires_at'], name='orcid_app_o_expires_2b3135_idx'),
        ),
    ]
