# Generated by Django 5.2.7 on 2025-11-15 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FigurePanel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("A", "Panel A"),
                            ("B", "Panel B"),
                            ("C", "Panel C"),
                            ("D", "Panel D"),
                            ("E", "Panel E"),
                            ("F", "Panel F"),
                            ("G", "Panel G"),
                            ("H", "Panel H"),
                        ],
                        max_length=1,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "source_image",
                    models.ImageField(null=True, upload_to="vis/panels/%Y/%m/"),
                ),
                (
                    "source_metadata",
                    models.FileField(
                        blank=True,
                        help_text="JSON metadata from scitex.plt",
                        null=True,
                        upload_to="vis/metadata/%Y/%m/",
                    ),
                ),
                ("x", models.IntegerField(default=0)),
                ("y", models.IntegerField(default=0)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                (
                    "locked",
                    models.BooleanField(
                        default=True, help_text="Lock base image position"
                    ),
                ),
                (
                    "data_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash for file tracking",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "position"],
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("significance", "Statistical Significance (***,**,*)"),
                            ("scalebar", "Scale Bar"),
                            ("arrow", "Arrow"),
                            ("line", "Line"),
                            ("rectangle", "Rectangle"),
                            ("ellipse", "Ellipse"),
                            ("label", "Panel Label (A, B, C)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Text content if applicable"
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                (
                    "style",
                    models.JSONField(
                        default=dict,
                        help_text="Font, color, size, etc. Stored as Fabric.js properties",
                    ),
                ),
                (
                    "scale_length_um",
                    models.FloatField(
                        blank=True,
                        help_text="Scale bar length in micrometers",
                        null=True,
                    ),
                ),
                (
                    "pixels_per_unit",
                    models.FloatField(
                        blank=True, help_text="Calibration: pixels per unit", null=True
                    ),
                ),
                ("z_index", models.IntegerField(default=0, help_text="Layer order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="vis_app.figurepanel",
                    ),
                ),
            ],
            options={
                "ordering": ["z_index", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "column_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Column"),
                            ("double", "Double Column"),
                            ("full", "Full Page"),
                        ],
                        max_length=20,
                    ),
                ),
                ("width_mm", models.FloatField(help_text="Width in millimeters")),
                (
                    "height_mm",
                    models.FloatField(
                        blank=True, help_text="Height in mm (null = auto)", null=True
                    ),
                ),
                ("dpi", models.IntegerField(default=300)),
                ("font_family", models.CharField(default="Arial", max_length=50)),
                (
                    "font_size_pt",
                    models.FloatField(default=7, help_text="Font size in points"),
                ),
                (
                    "line_width_pt",
                    models.FloatField(
                        default=0.5, help_text="Default line width in points"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name", "column_type"],
                "unique_together": {("name", "column_type")},
            },
        ),
        migrations.CreateModel(
            name="ScientificFigure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("1x1", "Single Panel"),
                            ("2x1", "Two Horizontal"),
                            ("1x2", "Two Vertical"),
                            ("2x2", "Four Panel Grid"),
                            ("1x3", "Three Horizontal"),
                            ("3x1", "Three Vertical"),
                            ("2x3", "Six Panel Grid"),
                            ("custom", "Custom Layout"),
                        ],
                        default="1x1",
                        max_length=20,
                    ),
                ),
                ("canvas_width_px", models.IntegerField(blank=True, null=True)),
                ("canvas_height_px", models.IntegerField(blank=True, null=True)),
                ("canvas_dpi", models.IntegerField(default=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("editing", "Editing"),
                            ("final", "Final"),
                            ("exported", "Exported"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "canvas_state",
                    models.JSONField(
                        default=dict, help_text="Complete Fabric.js canvas state"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_exported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "journal_preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vis_app.journalpreset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scientific_figures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="figurepanel",
            name="figure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="panels",
                to="vis_app.scientificfigure",
            ),
        ),
        migrations.CreateModel(
            name="FigureExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("png", "PNG (Raster)"),
                            ("svg", "SVG (Vector)"),
                            ("pdf", "PDF"),
                            ("tiff", "TIFF"),
                        ],
                        max_length=10,
                    ),
                ),
                ("dpi", models.IntegerField(default=300)),
                ("width_mm", models.FloatField(blank=True, null=True)),
                ("height_mm", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="vis/exports/%Y/%m/"
                    ),
                ),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "figure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="vis_app.scientificfigure",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="scientificfigure",
            index=models.Index(
                fields=["owner", "status"], name="vis_app_sci_owner_i_080e5d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="figurepanel",
            unique_together={("figure", "position")},
        ),
    ]
