# Generated by Django 5.2.7 on 2025-11-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vis_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalpreset",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
