# Generated by Django 5.2.7 on 2025-11-16 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vis_app", "0002_alter_journalpreset_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FigureVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_type",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("snapshot", "Snapshot"),
                            ("auto", "Auto-save"),
                        ],
                        default="snapshot",
                        max_length=20,
                    ),
                ),
                ("version_number", models.IntegerField(default=1)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="User-defined label for this version",
                        max_length=100,
                    ),
                ),
                (
                    "canvas_state",
                    models.JSONField(
                        default=dict,
                        help_text="Complete Fabric.js canvas state at this version",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="vis/previews/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "figure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="vis_app.scientificfigure",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["figure", "version_type"],
                        name="vis_app_fig_figure__197584_idx",
                    )
                ],
            },
        ),
    ]
