# Generated by Django 4.2.11 on 2025-06-29 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholar_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MendeleyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mendeley_id', models.CharField(help_text='Mendeley document ID', max_length=100)),
                ('title', models.TextField(help_text='Document title')),
                ('document_type', models.CharField(choices=[('journal', 'Journal Article'), ('book', 'Book'), ('book_section', 'Book Section'), ('conference_proceedings', 'Conference Proceedings'), ('working_paper', 'Working Paper'), ('report', 'Report'), ('web_page', 'Web Page'), ('thesis', 'Thesis'), ('magazine_article', 'Magazine Article'), ('statute', 'Statute'), ('patent', 'Patent'), ('newspaper_article', 'Newspaper Article'), ('computer_program', 'Computer Program'), ('hearing', 'Hearing'), ('television_broadcast', 'Television Broadcast'), ('encyclopedia_article', 'Encyclopedia Article'), ('case', 'Case'), ('film', 'Film'), ('bill', 'Bill'), ('generic', 'Generic')], default='journal', max_length=50)),
                ('year', models.IntegerField(blank=True, help_text='Publication year', null=True)),
                ('month', models.IntegerField(blank=True, help_text='Publication month', null=True)),
                ('day', models.IntegerField(blank=True, help_text='Publication day', null=True)),
                ('source', models.CharField(blank=True, help_text='Journal or publication source', max_length=500)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=100)),
                ('abstract', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='User notes from Mendeley')),
                ('authors', models.JSONField(blank=True, default=list, help_text='List of authors')),
                ('editors', models.JSONField(blank=True, default=list, help_text='List of editors')),
                ('doi', models.CharField(blank=True, db_index=True, max_length=255)),
                ('pmid', models.CharField(blank=True, help_text='PubMed ID', max_length=20)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('issn', models.CharField(blank=True, max_length=9)),
                ('arxiv', models.CharField(blank=True, help_text='ArXiv ID', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('mendeley_url', models.URLField(blank=True, help_text='Mendeley document URL')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Document tags')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Keywords')),
                ('file_attached', models.BooleanField(default=False, help_text='Document has attached file')),
                ('created', models.DateTimeField(blank=True, help_text='Created date in Mendeley', null=True)),
                ('last_modified', models.DateTimeField(blank=True, help_text='Last modified date in Mendeley', null=True)),
                ('mendeley_raw_data', models.JSONField(blank=True, default=dict, help_text='Raw Mendeley API response')),
                ('is_imported', models.BooleanField(default=False, help_text='Imported into Scholar module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mendeley Document',
                'verbose_name_plural': 'Mendeley Documents',
                'ordering': ['-year', '-created', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MendeleyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mendeley_id', models.CharField(help_text='Mendeley user ID', max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='Display name', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('academic_status', models.CharField(blank=True, help_text='Academic status (e.g., Professor, Student)', max_length=100)),
                ('discipline', models.CharField(blank=True, help_text='Research discipline', max_length=255)),
                ('institution', models.CharField(blank=True, help_text='Current institution', max_length=500)),
                ('link', models.URLField(blank=True, help_text='Mendeley profile URL')),
                ('is_synced', models.BooleanField(default=False, help_text='Profile has been synced with Mendeley')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_documents', models.BooleanField(default=True, help_text='Auto-sync documents from Mendeley')),
                ('auto_sync_enabled', models.BooleanField(default=True, help_text='Enable automatic periodic sync')),
                ('public_profile', models.BooleanField(default=True, help_text='Make Mendeley profile visible to other users')),
                ('show_documents', models.BooleanField(default=True, help_text='Show Mendeley documents in Scholar')),
                ('mendeley_record', models.JSONField(blank=True, default=dict, help_text='Raw Mendeley profile data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mendeley_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mendeley Profile',
                'verbose_name_plural': 'Mendeley Profiles',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MendeleyOAuth2Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='Mendeley access token', max_length=500)),
                ('refresh_token', models.CharField(blank=True, help_text='Mendeley refresh token', max_length=500)),
                ('token_type', models.CharField(default='bearer', max_length=50)),
                ('scope', models.CharField(help_text='OAuth scope granted', max_length=255)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mendeley_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mendeley OAuth2 Token',
                'verbose_name_plural': 'Mendeley OAuth2 Tokens',
            },
        ),
        migrations.CreateModel(
            name='MendeleyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mendeley_group_id', models.CharField(help_text='Mendeley group ID', max_length=100)),
                ('name', models.CharField(help_text='Group name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('group_type', models.CharField(blank=True, help_text='Type of group (private, public, etc.)', max_length=50)),
                ('role', models.CharField(blank=True, help_text="User's role in group", max_length=50)),
                ('access_level', models.CharField(blank=True, help_text='Access level', max_length=50)),
                ('sync_enabled', models.BooleanField(default=True, help_text='Sync documents from this group')),
                ('mendeley_raw_data', models.JSONField(blank=True, default=dict, help_text='Raw Mendeley group data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mendeley_groups', to='mendeley_app.mendeleyprofile')),
            ],
            options={
                'verbose_name': 'Mendeley Group',
                'verbose_name_plural': 'Mendeley Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MendeleyFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mendeley_folder_id', models.CharField(help_text='Mendeley folder ID', max_length=100)),
                ('name', models.CharField(help_text='Folder name', max_length=255)),
                ('mendeley_raw_data', models.JSONField(blank=True, default=dict, help_text='Raw Mendeley folder data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='folders', to='mendeley_app.mendeleydocument')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='mendeley_app.mendeleyfolder')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mendeley_folders', to='mendeley_app.mendeleyprofile')),
            ],
            options={
                'verbose_name': 'Mendeley Folder',
                'verbose_name_plural': 'Mendeley Folders',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mendeleydocument',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mendeley_documents', to='mendeley_app.mendeleyprofile'),
        ),
        migrations.AddField(
            model_name='mendeleydocument',
            name='scholar_paper',
            field=models.ForeignKey(blank=True, help_text='Linked Scholar paper', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mendeley_documents', to='scholar_app.searchindex'),
        ),
        migrations.CreateModel(
            name='MendeleySyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('profile', 'Profile Sync'), ('documents', 'Documents Sync'), ('groups', 'Groups Sync'), ('folders', 'Folders Sync'), ('full', 'Full Sync')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_created', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('items_skipped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='mendeley_app.mendeleyprofile')),
            ],
            options={
                'verbose_name': 'Mendeley Sync Log',
                'verbose_name_plural': 'Mendeley Sync Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['profile', '-started_at'], name='mendeley_ap_profile_0cbb87_idx'), models.Index(fields=['status'], name='mendeley_ap_status_fc4755_idx'), models.Index(fields=['sync_type'], name='mendeley_ap_sync_ty_94030e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mendeleyprofile',
            index=models.Index(fields=['mendeley_id'], name='mendeley_ap_mendele_5f50c9_idx'),
        ),
        migrations.AddIndex(
            model_name='mendeleyprofile',
            index=models.Index(fields=['user'], name='mendeley_ap_user_id_78f985_idx'),
        ),
        migrations.AddIndex(
            model_name='mendeleyprofile',
            index=models.Index(fields=['last_sync_at'], name='mendeley_ap_last_sy_157917_idx'),
        ),
        migrations.AddIndex(
            model_name='mendeleyoauth2token',
            index=models.Index(fields=['user'], name='mendeley_ap_user_id_a445cd_idx'),
        ),
        migrations.AddIndex(
            model_name='mendeleyoauth2token',
            index=models.Index(fields=['expires_at'], name='mendeley_ap_expires_17646e_idx'),
        ),
        migrations.AddIndex(
            model_name='mendeleygroup',
            index=models.Index(fields=['profile'], name='mendeley_ap_profile_a964ea_idx'),
        ),
        migrations.AddIndex(
            model_name='mendeleygroup',
            index=models.Index(fields=['mendeley_group_id'], name='mendeley_ap_mendele_61ef2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mendeleygroup',
            unique_together={('profile', 'mendeley_group_id')},
        ),
        migrations.AddIndex(
            model_name='mendeleyfolder',
            index=models.Index(fields=['profile'], name='mendeley_ap_profile_969c66_idx'),
        ),
        migrations.AddIndex(
            model_name='mendeleyfolder',
            index=models.Index(fields=['mendeley_folder_id'], name='mendeley_ap_mendele_ec0221_idx'),
        ),
        migrations.AddIndex(
            model_name='mendeleyfolder',
            index=models.Index(fields=['parent_folder'], name='mendeley_ap_parent__a19259_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mendeleyfolder',
            unique_together={('profile', 'mendeley_folder_id')},
        ),
        migrations.AddIndex(
            model_name='mendeleydocument',
            index=models.Index(fields=['profile', '-year'], name='mendeley_ap_profile_d3e935_idx'),
        ),
        migrations.AddIndex(
            model_name='mendeleydocument',
            index=models.Index(fields=['doi'], name='mendeley_ap_doi_6f8c28_idx'),
        ),
        migrations.AddIndex(
            model_name='mendeleydocument',
            index=models.Index(fields=['pmid'], name='mendeley_ap_pmid_5f1de8_idx'),
        ),
        migrations.AddIndex(
            model_name='mendeleydocument',
            index=models.Index(fields=['document_type'], name='mendeley_ap_documen_b85d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='mendeleydocument',
            index=models.Index(fields=['is_imported'], name='mendeley_ap_is_impo_ff39d3_idx'),
        ),
        migrations.AddIndex(
            model_name='mendeleydocument',
            index=models.Index(fields=['created'], name='mendeley_ap_created_8c183b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mendeleydocument',
            unique_together={('profile', 'mendeley_id')},
        ),
    ]
