# Generated by Django 5.2.7 on 2025-10-17 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project_app", "0005_project_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("follow", "Followed user"),
                            ("star", "Starred repository"),
                            ("create_project", "Created repository"),
                            ("fork", "Forked repository"),
                            ("commit", "Committed to repository"),
                            ("issue", "Created issue"),
                            ("pr", "Created pull request"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional activity metadata (commit message, issue title, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target project (for star, fork, commit actions)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_activities",
                        to="project_app.project",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target user (for follow actions)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="social_app__user_id_6f4a0a_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-created_at"],
                        name="social_app__activit_b7c737_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RepositoryStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Repository that was starred",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stars",
                        to="project_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who starred the repository",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starred_repositories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-starred_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-starred_at"],
                        name="social_app__user_id_9d5a28_idx",
                    ),
                    models.Index(
                        fields=["project", "-starred_at"],
                        name="social_app__project_f0bc13_idx",
                    ),
                ],
                "unique_together": {("user", "project")},
            },
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        help_text="User who is following",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        help_text="User being followed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["follower", "-created_at"],
                        name="social_app__followe_fe2753_idx",
                    ),
                    models.Index(
                        fields=["following", "-created_at"],
                        name="social_app__followi_30c106_idx",
                    ),
                ],
                "unique_together": {("follower", "following")},
            },
        ),
    ]
