# Generated by Django 4.2.11 on 2025-06-27 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=200)),
                ('response_time', models.FloatField()),
                ('status_code', models.IntegerField()),
                ('success', models.BooleanField()),
                ('query_params', models.JSONField(default=dict)),
                ('response_size', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['api_name', 'timestamp'], name='monitoring__api_nam_9ced70_idx'), models.Index(fields=['success', 'timestamp'], name='monitoring__success_3ef3da_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('search', 'Search'), ('document_create', 'Document Create'), ('document_edit', 'Document Edit'), ('project_create', 'Project Create'), ('visualization_create', 'Visualization Create'), ('code_execute', 'Code Execute')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('session_id', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='monitoring__user_id_aea825_idx'), models.Index(fields=['activity_type', 'timestamp'], name='monitoring__activit_d70d40_idx'), models.Index(fields=['session_id', 'timestamp'], name='monitoring__session_ca9000_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('response_time', 'Response Time'), ('api_call', 'API Call'), ('error_rate', 'Error Rate'), ('user_action', 'User Action'), ('database_query', 'Database Query')], max_length=20)),
                ('endpoint', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.FloatField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='monitoring__metric__19d337_idx'), models.Index(fields=['endpoint', 'timestamp'], name='monitoring__endpoin_f56e24_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('error_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=200, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['severity', 'timestamp'], name='monitoring__severit_3aa799_idx'), models.Index(fields=['error_type', 'timestamp'], name='monitoring__error_t_39b061_idx'), models.Index(fields=['resolved', 'timestamp'], name='monitoring__resolve_5bf27a_idx')],
            },
        ),
    ]
