# Generated by Django 4.2.11 on 2025-06-27 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('scholar', 'Scholar'), ('writer', 'Writer'), ('viz', 'Visualization'), ('code', 'Code'), ('dashboard', 'Dashboard')], max_length=20)),
                ('feature_name', models.CharField(max_length=100)),
                ('usage_count', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('avg_session_time', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=100.0)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('daily_usage', models.JSONField(default=dict)),
                ('weekly_growth', models.FloatField(default=0.0)),
                ('monthly_growth', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('avg_session_duration', models.FloatField(default=0.0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('scholar_searches', models.IntegerField(default=0)),
                ('scholar_saves', models.IntegerField(default=0)),
                ('writer_compiles', models.IntegerField(default=0)),
                ('writer_templates_used', models.IntegerField(default=0)),
                ('viz_created', models.IntegerField(default=0)),
                ('viz_exported', models.IntegerField(default=0)),
                ('code_executions', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('feature_adoption_rate', models.FloatField(default=0.0)),
                ('retention_score', models.FloatField(default=0.0)),
                ('preferred_module', models.CharField(blank=True, max_length=20, null=True)),
                ('peak_usage_hour', models.IntegerField(blank=True, null=True)),
                ('consecutive_days', models.IntegerField(default=0)),
                ('max_consecutive_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='useractivity',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='feature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='module',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('search', 'Search'), ('document_create', 'Document Create'), ('document_edit', 'Document Edit'), ('project_create', 'Project Create'), ('visualization_create', 'Visualization Create'), ('code_execute', 'Code Execute'), ('scholar_search', 'Scholar Search'), ('scholar_save', 'Scholar Save Paper'), ('writer_compile', 'Writer Compile'), ('writer_template', 'Writer Template Use'), ('viz_create', 'Visualization Create'), ('viz_export', 'Visualization Export'), ('code_run', 'Code Run'), ('dashboard_view', 'Dashboard View'), ('profile_update', 'Profile Update'), ('feature_use', 'Feature Use')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['module', 'timestamp'], name='monitoring__module_9d45fa_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['feature', 'timestamp'], name='monitoring__feature_f785f5_idx'),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['module', 'usage_count'], name='monitoring__module_6130bb_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['feature_name', 'usage_count'], name='monitoring__feature_14b96e_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['last_used'], name='monitoring__last_us_73193e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featureusage',
            unique_together={('module', 'feature_name')},
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['engagement_score'], name='monitoring__engagem_6e5c97_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['feature_adoption_rate'], name='monitoring__feature_4fb560_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['last_activity'], name='monitoring__last_ac_08a888_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['preferred_module'], name='monitoring__preferr_cb36cd_idx'),
        ),
    ]
