# Generated by Django 5.2.7 on 2025-10-17 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project_app", "0004_alter_project_collaborators"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("orcid", "ORCID"),
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("zotero", "Zotero"),
                            ("overleaf", "Overleaf"),
                            ("slack", "Slack"),
                            ("discord", "Discord"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("expired", "Expired"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True, help_text="Encrypted OAuth access token"
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True, help_text="Encrypted OAuth refresh token"
                    ),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "api_key",
                    models.TextField(blank=True, help_text="Encrypted API key"),
                ),
                (
                    "api_secret",
                    models.TextField(blank=True, help_text="Encrypted API secret"),
                ),
                (
                    "external_user_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID on external service",
                        max_length=255,
                    ),
                ),
                ("external_username", models.CharField(blank=True, max_length=255)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Service-specific metadata"
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True, help_text="Webhook URL for notifications"
                    ),
                ),
                (
                    "webhook_secret",
                    models.TextField(blank=True, help_text="Encrypted webhook secret"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration Connection",
                "verbose_name_plural": "Integration Connections",
                "unique_together": {("user", "service")},
            },
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("connect", "Connected"),
                            ("disconnect", "Disconnected"),
                            ("sync", "Synced"),
                            ("export", "Exported"),
                            ("import", "Imported"),
                            ("notify", "Notification Sent"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="integrations_app.integrationconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration Log",
                "verbose_name_plural": "Integration Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ORCIDProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orcid_id",
                    models.CharField(
                        help_text="ORCID iD (e.g., 0000-0002-1825-0097)",
                        max_length=19,
                        unique=True,
                    ),
                ),
                ("given_names", models.CharField(blank=True, max_length=255)),
                ("family_name", models.CharField(blank=True, max_length=255)),
                ("biography", models.TextField(blank=True)),
                ("current_institution", models.CharField(blank=True, max_length=255)),
                ("affiliations", models.JSONField(blank=True, default=list)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("profile_url", models.URLField(blank=True)),
                ("website_urls", models.JSONField(blank=True, default=list)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orcid_profile",
                        to="integrations_app.integrationconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "ORCID Profile",
                "verbose_name_plural": "ORCID Profiles",
            },
        ),
        migrations.CreateModel(
            name="SlackWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webhook_url", models.URLField(help_text="Slack webhook URL")),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        help_text="Target channel (optional)",
                        max_length=100,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        default="SciTeX", help_text="Bot username", max_length=100
                    ),
                ),
                (
                    "icon_emoji",
                    models.CharField(
                        default=":microscope:",
                        help_text="Bot icon emoji",
                        max_length=50,
                    ),
                ),
                (
                    "enabled_events",
                    models.JSONField(
                        default=list, help_text="List of event types to notify"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_notification_at", models.DateTimeField(blank=True, null=True)),
                ("notification_count", models.IntegerField(default=0)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_webhooks",
                        to="integrations_app.integrationconnection",
                    ),
                ),
                (
                    "project_filter",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Only notify for these projects (empty = all)",
                        related_name="slack_webhooks",
                        to="project_app.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Webhook",
                "verbose_name_plural": "Slack Webhooks",
            },
        ),
    ]
