# Generated by Django 5.2.7 on 2025-11-14 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWorkspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "container_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_running", models.BooleanField(default=False)),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_stopped_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("cpu_limit", models.IntegerField(default=200000)),
                ("memory_limit", models.BigIntegerField(default=8589934592)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Workspace",
                "verbose_name_plural": "User Workspaces",
                "db_table": "workspace_user_workspace",
                "ordering": ["-last_activity_at"],
            },
        ),
    ]
