# Generated by Django 4.2.11 on 2025-10-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="Profile picture", null=True, upload_to="avatars/"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Your current location (e.g., 'Tokyo, Japan')",
                max_length=200,
            ),
        ),
    ]
