# Generated by Django 5.2.7 on 2025-10-17 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace_app", "0002_userprofile_avatar_userprofile_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="collaborative_projects",
                through="workspace_app.ProjectMembership",
                through_fields=("project", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
