# Generated by Django 5.2.7 on 2025-10-17 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0004_userprofile_last_active_project"),
        ("project_app", "0004_alter_project_collaborators"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="last_active_project",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_active_repository",
            field=models.ForeignKey(
                blank=True,
                help_text="Last repository the user was working on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_active_for_users",
                to="project_app.project",
            ),
        ),
    ]
