# Generated by Django 5.2.7 on 2025-10-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspace_app", "0005_remove_userprofile_last_active_project_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
