# Generated by Django 5.2.7 on 2025-10-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspace_app", "0006_delete_userprofile"),
    ]

    operations = [
        # Drop unique_together constraints BEFORE removing fields they reference
        migrations.AlterUniqueTogether(
            name="organizationmembership",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="researchgroup",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="researchgroupmembership",
            unique_together=None,
        ),
        # Now remove fields
        migrations.RemoveField(
            model_name="organization",
            name="members",
        ),
        migrations.RemoveField(
            model_name="organizationmembership",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="organizationmembership",
            name="user",
        ),
        migrations.RemoveField(
            model_name="researchgroup",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="researchgroup",
            name="admins",
        ),
        migrations.RemoveField(
            model_name="researchgroup",
            name="members",
        ),
        migrations.RemoveField(
            model_name="researchgroup",
            name="principal_investigator",
        ),
        migrations.RemoveField(
            model_name="researchgroupmembership",
            name="group",
        ),
        migrations.RemoveField(
            model_name="researchgroupmembership",
            name="user",
        ),
        migrations.DeleteModel(
            name="GitFileStatus",
        ),
        migrations.DeleteModel(
            name="Manuscript",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectMembership",
        ),
        migrations.DeleteModel(
            name="ProjectPermission",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="OrganizationMembership",
        ),
        migrations.DeleteModel(
            name="ResearchGroup",
        ),
        migrations.DeleteModel(
            name="ResearchGroupMembership",
        ),
    ]
