# Generated by Django 5.2.7 on 2025-10-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile_app",
            "0003_userprofile_bitbucket_token_userprofile_github_token_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bitbucket_profile",
            field=models.CharField(
                blank=True, help_text="Your Bitbucket username", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_profile",
            field=models.CharField(
                blank=True, help_text="Your GitHub username", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gitlab_profile",
            field=models.CharField(
                blank=True, help_text="Your GitLab username", max_length=100
            ),
        ),
    ]
