# Generated by Django 5.2.7 on 2025-10-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_app", "0004_add_git_hosting_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="UTC",
                help_text="Your timezone (e.g., 'Asia/Tokyo')",
                max_length=100,
            ),
        ),
    ]
