# Generated by Django 5.2.7 on 2025-10-17 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project_app", "0004_alter_project_collaborators"),
        ("writer_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("guest_name", models.CharField(blank=True, max_length=200)),
                (
                    "access_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("maintainer", "Maintainer"),
                            ("developer", "Developer"),
                            ("reporter", "Reporter"),
                            ("guest", "Guest"),
                        ],
                        default="guest",
                        max_length=20,
                    ),
                ),
                ("can_comment", models.BooleanField(default=True)),
                ("can_download", models.BooleanField(default=True)),
                ("invitation_sent_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("first_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.IntegerField(default=0)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_collaborators",
                        to="writer_app.manuscript",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_collaborators",
                        to="project_app.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-invitation_sent_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("maintainer", "Maintainer"),
                            ("developer", "Developer"),
                            ("reporter", "Reporter"),
                            ("guest", "Guest"),
                        ],
                        default="developer",
                        max_length=20,
                    ),
                ),
                ("can_edit_scholar", models.BooleanField(blank=True, null=True)),
                ("can_edit_code", models.BooleanField(blank=True, null=True)),
                ("can_edit_viz", models.BooleanField(blank=True, null=True)),
                ("can_edit_writer", models.BooleanField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_members",
                        to="project_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "unique_together": {("project", "user")},
            },
        ),
    ]
