# Generated by Django 4.2.11 on 2025-06-29 13:36

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('template_type', models.CharField(choices=[('literature_review', 'Literature Review'), ('research_paper', 'Research Paper'), ('data_analysis', 'Data Analysis Project'), ('collaboration', 'Team Collaboration'), ('thesis', 'Thesis Project'), ('grant_proposal', 'Grant Proposal'), ('conference_paper', 'Conference Paper'), ('journal_article', 'Journal Article')], max_length=30)),
                ('research_field', models.CharField(choices=[('computer_science', 'Computer Science'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('medicine', 'Medicine'), ('psychology', 'Psychology'), ('economics', 'Economics'), ('engineering', 'Engineering'), ('mathematics', 'Mathematics'), ('social_sciences', 'Social Sciences'), ('humanities', 'Humanities'), ('interdisciplinary', 'Interdisciplinary')], default='interdisciplinary', max_length=30)),
                ('project_structure', models.JSONField(default=dict, help_text='Directory structure and files')),
                ('sample_content', models.JSONField(default=dict, help_text='Sample file contents')),
                ('guided_steps', models.JSONField(default=list, help_text='Step-by-step guidance')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_time', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['template_type', 'difficulty_level'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tip_type', models.CharField(choices=[('welcome', 'Welcome Tips'), ('navigation', 'Navigation Help'), ('feature', 'Feature Introduction'), ('workflow', 'Workflow Guidance'), ('best_practice', 'Best Practices'), ('troubleshooting', 'Troubleshooting')], default='feature', max_length=20)),
                ('target_page', models.CharField(help_text='URL pattern or page identifier', max_length=100)),
                ('target_element', models.CharField(blank=True, help_text='CSS selector for target element', max_length=100)),
                ('trigger_condition', models.CharField(choices=[('page_load', 'On Page Load'), ('first_visit', 'First Visit to Page'), ('idle_time', 'After Idle Time'), ('error_state', 'On Error'), ('feature_hover', 'On Feature Hover'), ('manual', 'Manual Trigger')], default='page_load', max_length=20)),
                ('position', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('auto', 'Auto')], default='auto', max_length=20)),
                ('priority', models.IntegerField(default=1, help_text='Higher numbers show first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.IntegerField(default=0)),
                ('dismiss_count', models.IntegerField(default=0)),
                ('action_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_tooltips', models.BooleanField(default=True)),
                ('show_guided_tours', models.BooleanField(default=True)),
                ('show_progress_tracker', models.BooleanField(default=True)),
                ('show_achievements', models.BooleanField(default=True)),
                ('email_onboarding_tips', models.BooleanField(default=True)),
                ('email_achievement_notifications', models.BooleanField(default=True)),
                ('email_feature_updates', models.BooleanField(default=True)),
                ('preferred_learning_style', models.CharField(choices=[('visual', 'Visual Learner'), ('hands_on', 'Hands-on Learner'), ('reading', 'Reading Learner'), ('minimal', 'Minimal Guidance')], default='visual', max_length=20)),
                ('tutorial_pace', models.CharField(choices=[('slow', 'Slow and Detailed'), ('medium', 'Medium Pace'), ('fast', 'Quick Overview'), ('custom', 'Let Me Control')], default='medium', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('first_visit', 'First Visit'), ('returning_user', 'Returning User'), ('feature_discovery', 'Feature Discovery'), ('help_seeking', 'Help Seeking')], default='first_visit', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('pages_visited', models.JSONField(default=list)),
                ('actions_taken', models.JSONField(default=list)),
                ('features_explored', models.JSONField(default=list)),
                ('completed_steps', models.JSONField(default=list)),
                ('achievements_earned', models.JSONField(default=list)),
                ('satisfaction_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('welcome', 'Welcome & Introduction'), ('profile_setup', 'Profile Setup'), ('first_project', 'Create First Project'), ('first_search', 'First Literature Search'), ('first_document', 'Create First Document'), ('completed', 'Onboarding Completed')], default='welcome', max_length=30)),
                ('completed_steps', models.JSONField(default=list, help_text='List of completed step names')),
                ('completion_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('show_tips', models.BooleanField(default=True, help_text='Show contextual tips')),
                ('session_count', models.IntegerField(default=0)),
                ('total_time_spent', models.DurationField(default=datetime.timedelta)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_login', 'First Login'), ('profile_complete', 'Profile Complete'), ('first_project', 'First Project Created'), ('first_search', 'First Literature Search'), ('first_document', 'First Document Created'), ('first_collaboration', 'First Team Collaboration'), ('power_user', 'Power User (10+ projects)'), ('researcher', 'Active Researcher (50+ searches)'), ('author', 'Prolific Author (10+ documents)'), ('collaborator', 'Team Player (5+ collaborations)'), ('explorer', 'Module Explorer (all modules used)'), ('mentor', 'Community Mentor (helped others)'), ('expert', 'Domain Expert (advanced features used)'), ('pioneer', 'Early Adopter'), ('contributor', 'Platform Contributor'), ('advocate', 'Platform Advocate')], max_length=30)),
                ('category', models.CharField(choices=[('getting_started', 'Getting Started'), ('productivity', 'Productivity'), ('collaboration', 'Collaboration'), ('expertise', 'Expertise'), ('community', 'Community'), ('special', 'Special Recognition')], default='getting_started', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fa-trophy', help_text='FontAwesome icon class', max_length=50)),
                ('points', models.IntegerField(default=10, help_text='Points awarded for this achievement')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional achievement data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
