# Generated by Django 5.2.7 on 2025-10-17 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=200)),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("users", "Users"),
                            ("repositories", "Repositories"),
                            ("code", "Code"),
                            ("papers", "Papers"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("results_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="global_search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["query", "-created_at"],
                        name="search_app__query_e86ffc_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="search_app__user_id_733ce9_idx",
                    ),
                ],
            },
        ),
    ]
