# Generated by Django 5.2.7 on 2025-10-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project_app", "0009_project_gitea_clone_url_project_gitea_repo_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitFileStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Relative path from project root", max_length=500
                    ),
                ),
                (
                    "git_status",
                    models.CharField(
                        choices=[
                            ("untracked", "Untracked"),
                            ("modified", "Modified"),
                            ("added", "Added"),
                            ("deleted", "Deleted"),
                            ("renamed", "Renamed"),
                            ("copied", "Copied"),
                            ("staged", "Staged"),
                            ("committed", "Committed"),
                        ],
                        default="untracked",
                        max_length=20,
                    ),
                ),
                (
                    "last_commit_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA of last commit affecting this file",
                        max_length=40,
                    ),
                ),
                (
                    "last_commit_message",
                    models.CharField(
                        blank=True, help_text="Last commit message", max_length=200
                    ),
                ),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="File size in bytes"),
                ),
                (
                    "is_binary",
                    models.BooleanField(
                        default=False, help_text="Whether file is binary"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_files",
                        to="project_app.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Git File Status",
                "verbose_name_plural": "Git File Statuses",
                "ordering": ["file_path"],
                "indexes": [
                    models.Index(
                        fields=["project", "git_status"],
                        name="gitea_app_g_project_4ffc45_idx",
                    ),
                    models.Index(
                        fields=["project", "file_path"],
                        name="gitea_app_g_project_e515a0_idx",
                    ),
                ],
                "unique_together": {("project", "file_path")},
            },
        ),
    ]
