# Generated by Django 4.2.11 on 2025-10-15 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Project progress percentage (0-100)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "hypotheses",
                    models.TextField(help_text="Research hypotheses (required)"),
                ),
                (
                    "source_code_url",
                    models.URLField(
                        blank=True, help_text="GitHub/GitLab repository URL"
                    ),
                ),
                (
                    "data_location",
                    models.CharField(
                        blank=True,
                        help_text="Relative path to project directory",
                        max_length=500,
                    ),
                ),
                (
                    "github_token",
                    models.CharField(
                        blank=True, help_text="GitHub OAuth token", max_length=255
                    ),
                ),
                (
                    "github_repo_id",
                    models.IntegerField(
                        blank=True, help_text="GitHub repository ID", null=True
                    ),
                ),
                (
                    "github_repo_name",
                    models.CharField(
                        blank=True, help_text="GitHub repository name", max_length=200
                    ),
                ),
                (
                    "github_owner",
                    models.CharField(
                        blank=True, help_text="GitHub repository owner", max_length=100
                    ),
                ),
                (
                    "current_branch",
                    models.CharField(
                        default="main", help_text="Current git branch", max_length=100
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, help_text="Last GitHub sync timestamp", null=True
                    ),
                ),
                (
                    "github_integration_enabled",
                    models.BooleanField(
                        default=False, help_text="GitHub integration status"
                    ),
                ),
                (
                    "directory_created",
                    models.BooleanField(
                        default=False,
                        help_text="Whether project directory has been created",
                    ),
                ),
                (
                    "storage_used",
                    models.BigIntegerField(
                        default=0, help_text="Storage used by project in bytes"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, help_text="Last activity in project directory"
                    ),
                ),
                (
                    "search_completed",
                    models.BooleanField(
                        default=False, help_text="Literature search completed"
                    ),
                ),
                (
                    "knowledge_gap_identified",
                    models.TextField(blank=True, help_text="Identified knowledge gaps"),
                ),
                (
                    "analysis_completed",
                    models.BooleanField(
                        default=False, help_text="Code analysis completed"
                    ),
                ),
                (
                    "figures_generated",
                    models.BooleanField(
                        default=False, help_text="Visualizations generated"
                    ),
                ),
                (
                    "manuscript_generated",
                    models.BooleanField(
                        default=False, help_text="Manuscript generated"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Research group/lab name (e.g., 'Ikegaya Lab')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of research focus and goals"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Public group visibility"
                    ),
                ),
                (
                    "allow_external_collaborators",
                    models.BooleanField(
                        default=True, help_text="Allow external collaborators"
                    ),
                ),
                (
                    "auto_approve_internal",
                    models.BooleanField(
                        default=True, help_text="Auto-approve same organization members"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional admins (senior postdocs, co-PIs)",
                        related_name="administered_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of your research background",
                        max_length=500,
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True, help_text="Your current institution", max_length=200
                    ),
                ),
                (
                    "research_interests",
                    models.TextField(
                        blank=True,
                        help_text="Your research areas and interests",
                        max_length=500,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Your personal or professional website"
                    ),
                ),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        help_text="Your ORCID identifier (e.g., 0000-0000-0000-0000)",
                        max_length=19,
                    ),
                ),
                (
                    "academic_title",
                    models.CharField(
                        blank=True,
                        help_text="Your academic title (e.g., PhD, Professor)",
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Your department or faculty",
                        max_length=200,
                    ),
                ),
                (
                    "google_scholar",
                    models.URLField(
                        blank=True, help_text="Your Google Scholar profile"
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, help_text="Your LinkedIn profile"),
                ),
                (
                    "researchgate",
                    models.URLField(blank=True, help_text="Your ResearchGate profile"),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True,
                        help_text="Your Twitter handle (without @)",
                        max_length=50,
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("restricted", "Restricted"),
                            ("private", "Private"),
                        ],
                        default="public",
                        help_text="Who can view your profile",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, help_text="Make profile public"),
                ),
                (
                    "show_email",
                    models.BooleanField(
                        default=False, help_text="Show email in public profile"
                    ),
                ),
                (
                    "allow_collaboration",
                    models.BooleanField(
                        default=True, help_text="Allow collaboration requests"
                    ),
                ),
                (
                    "allow_messages",
                    models.BooleanField(
                        default=True, help_text="Allow messages from other users"
                    ),
                ),
                (
                    "is_academic_ja",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically detected: User belongs to Japanese academic institution",
                    ),
                ),
                (
                    "deletion_scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When account deletion was scheduled",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="ResearchGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("postdoc", "Postdoctoral Researcher"),
                            ("phd", "PhD Student"),
                            ("masters", "Masters Student"),
                            ("undergrad", "Undergraduate Student"),
                            ("researcher", "Research Staff"),
                            ("visiting", "Visiting Researcher"),
                            ("collaborator", "External Collaborator"),
                        ],
                        default="researcher",
                        max_length=20,
                    ),
                ),
                (
                    "can_create_projects",
                    models.BooleanField(
                        default=True, help_text="Can create new projects for the group"
                    ),
                ),
                (
                    "can_invite_collaborators",
                    models.BooleanField(
                        default=False, help_text="Can invite external collaborators"
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_app.researchgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "unique_together": {("user", "group")},
            },
        ),
        migrations.AddField(
            model_name="researchgroup",
            name="members",
            field=models.ManyToManyField(
                related_name="research_groups",
                through="core_app.ResearchGroupMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="researchgroup",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="research_groups",
                to="core_app.organization",
            ),
        ),
        migrations.AddField(
            model_name="researchgroup",
            name="principal_investigator",
            field=models.ForeignKey(
                help_text="PI/Lab head with full administrative control",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="led_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Project Owner"),
                            ("admin", "Project Administrator"),
                            ("editor", "Editor"),
                            ("collaborator", "Collaborator"),
                            ("viewer", "Viewer"),
                            ("reviewer", "External Reviewer"),
                        ],
                        default="collaborator",
                        max_length=20,
                    ),
                ),
                (
                    "can_read_files",
                    models.BooleanField(
                        default=True, help_text="Can read project files"
                    ),
                ),
                (
                    "can_write_files",
                    models.BooleanField(
                        default=False, help_text="Can modify project files"
                    ),
                ),
                (
                    "can_delete_files",
                    models.BooleanField(
                        default=False, help_text="Can delete project files"
                    ),
                ),
                (
                    "can_manage_collaborators",
                    models.BooleanField(
                        default=False, help_text="Can add/remove collaborators"
                    ),
                ),
                (
                    "can_edit_metadata",
                    models.BooleanField(
                        default=False,
                        help_text="Can edit project description, hypotheses",
                    ),
                ),
                (
                    "can_run_analysis",
                    models.BooleanField(
                        default=False, help_text="Can execute code and analysis"
                    ),
                ),
                (
                    "can_export_data",
                    models.BooleanField(
                        default=True, help_text="Can download/export project data"
                    ),
                ),
                (
                    "can_view_results",
                    models.BooleanField(
                        default=True, help_text="Can view analysis results"
                    ),
                ),
                (
                    "can_change_settings",
                    models.BooleanField(
                        default=False, help_text="Can modify project settings"
                    ),
                ),
                (
                    "can_archive_project",
                    models.BooleanField(
                        default=False, help_text="Can archive/delete project"
                    ),
                ),
                (
                    "access_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Temporary access expiration", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "access_granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who granted this access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "project")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="collaborative_projects",
                through="core_app.ProjectMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="core_app.organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="research_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated research group/lab",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="core_app.researchgroup",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_app.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "organization")},
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(
                through="core_app.OrganizationMembership", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="researchgroup",
            unique_together={("name", "organization")},
        ),
        migrations.CreateModel(
            name="ProjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="core_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "project")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("name", "owner")},
        ),
        migrations.CreateModel(
            name="Manuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="core_manuscripts",
                        to="core_app.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("project", "version")},
            },
        ),
        migrations.CreateModel(
            name="GitFileStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Relative path from project root", max_length=500
                    ),
                ),
                (
                    "git_status",
                    models.CharField(
                        choices=[
                            ("untracked", "Untracked"),
                            ("modified", "Modified"),
                            ("added", "Added"),
                            ("deleted", "Deleted"),
                            ("renamed", "Renamed"),
                            ("copied", "Copied"),
                            ("staged", "Staged"),
                            ("committed", "Committed"),
                        ],
                        default="untracked",
                        max_length=20,
                    ),
                ),
                (
                    "last_commit_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA of last commit affecting this file",
                        max_length=40,
                    ),
                ),
                (
                    "last_commit_message",
                    models.CharField(
                        blank=True, help_text="Last commit message", max_length=200
                    ),
                ),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="File size in bytes"),
                ),
                (
                    "is_binary",
                    models.BooleanField(
                        default=False, help_text="Whether file is binary"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_files",
                        to="core_app.project",
                    ),
                ),
            ],
            options={
                "ordering": ["file_path"],
                "indexes": [
                    models.Index(
                        fields=["project", "git_status"],
                        name="core_app_gi_project_5d1d26_idx",
                    ),
                    models.Index(
                        fields=["project", "file_path"],
                        name="core_app_gi_project_275a64_idx",
                    ),
                ],
                "unique_together": {("project", "file_path")},
            },
        ),
    ]
