# Generated by Django 4.2.11 on 2025-06-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0001_initial'),
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='manuscript_draft',
            field=models.ForeignKey(blank=True, help_text='Associated manuscript document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manuscripts', to='document_app.document'),
        ),
    ]
