# Generated by Django 4.2.11 on 2025-06-29 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_remove_document_owner_remove_document_project_and_more'),
        ('project_app', '0003_project_slug_alter_project_manuscript_draft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
