# Generated by Django 5.2.7 on 2025-10-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0003_alter_project_collaborators"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_active_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Last project the user was working on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_active_for_users",
                to="core_app.project",
            ),
        ),
    ]
