#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File: /home/ywatanabe/proj/scitex-cloud/apps/scholar_app/views/search/engines/semantic.py
# Auto-generated by refactoring script - search engines split
# ----------------------------------------
from __future__ import annotations
import os

__FILE__ = "./apps/scholar_app/views/search/engines/semantic.py"
__DIR__ = os.path.dirname(__FILE__)
# ----------------------------------------
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from django.core.cache import cache
import json
import requests
from scitex import logging
import asyncio
from datetime import datetime, timedelta
from ....models import SearchIndex, Journal, Author
from ..citations import get_journal_impact_factor, get_pubmed_citations, validate_citation_count
from ..search_helpers import search_database_papers, get_paper_authors
from ..storage import store_search_result

logger = logging.getLogger(__name__)

try:
    from scitex.scholar.pipelines.ScholarPipelineSearchParallel import ScholarPipelineSearchParallel
    SCITEX_SCHOLAR_AVAILABLE = True
except ImportError:
    SCITEX_SCHOLAR_AVAILABLE = False

def search_semantic_scholar(query, max_results=100, filters=None):
    """Search Semantic Scholar API with rate limiting."""
    try:
        base_url = "https://api.semanticscholar.org/graph/v1/paper/search"
        params = {
            "query": query,
            "limit": min(max_results, 10),  # Reduced to avoid rate limits
            "fields": "title,authors,year,journal,abstract,openAccessPdf,citationCount",
        }

        # Add delay to respect rate limits
        import time

        time.sleep(0.5)

        response = requests.get(base_url, params=params, timeout=10)
        response.raise_for_status()
        data = response.json()

        results = []
        if "data" in data:
            for paper in data["data"]:
                authors = []
                if "authors" in paper and paper["authors"]:
                    for author in paper["authors"][:3]:  # Limit to 3 authors
                        if "name" in author:
                            authors.append(author["name"])

                pdf_url = ""
                if paper.get("openAccessPdf") and paper["openAccessPdf"].get("url"):
                    pdf_url = paper["openAccessPdf"]["url"]

                journal_name = "Unknown Journal"
                if paper.get("journal") and paper["journal"].get("name"):
                    journal_name = paper["journal"]["name"]

                results.append(
                    {
                        "title": paper.get("title", "Unknown Title"),
                        "authors": ", ".join(authors),
                        "year": str(paper.get("year", "2024")),
                        "journal": journal_name,
                        "abstract": paper.get("abstract", ""),
                        "pdf_url": pdf_url,
                        "is_open_access": bool(pdf_url),
                        "citations": paper.get("citationCount", 0),
                        "source": "semantic_scholar",
                    }
                )

        return results

    except Exception as e:
        print(f"Error searching Semantic Scholar: {e}")
        return []





