# Generated by Django 4.2.11 on 2025-06-29 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_app', '0001_initial'),
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Team name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Team description and objectives')),
                ('team_type', models.CharField(choices=[('research', 'Research Team'), ('project', 'Project Team'), ('department', 'Department Team'), ('lab', 'Laboratory Team'), ('collaboration', 'Collaboration Team')], default='research', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('institution', 'Institution Only'), ('private', 'Private')], default='private', max_length=20)),
                ('allow_member_invites', models.BooleanField(default=False, help_text='Allow members to invite others')),
                ('require_approval', models.BooleanField(default=True, help_text='Require approval for new members')),
                ('max_members', models.IntegerField(default=50, help_text='Maximum number of team members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_teams', to=settings.AUTH_USER_MODEL)),
                ('associated_projects', models.ManyToManyField(blank=True, related_name='associated_teams', to='project_app.project')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to=settings.AUTH_USER_MODEL)),
                ('research_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.researchgroup')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_type', models.CharField(choices=[('view', 'View Only'), ('comment', 'Comment Only'), ('edit', 'Edit Access'), ('collaborate', 'Full Collaboration')], default='view', max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_instances', to='project_app.project')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_projects', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_projects', to='collaboration_app.team')),
            ],
            options={
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('review_type', models.CharField(choices=[('peer', 'Peer Review'), ('supervisor', 'Supervisor Review'), ('external', 'External Review'), ('self', 'Self Review')], default='peer', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Review Requested'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], default='requested', max_length=20)),
                ('decision', models.CharField(blank=True, choices=[('approve', 'Approved'), ('approve_with_changes', 'Approved with Changes'), ('revision_required', 'Revision Required'), ('reject', 'Rejected')], max_length=30, null=True)),
                ('summary', models.TextField(blank=True, help_text='Overall review summary')),
                ('detailed_feedback', models.TextField(blank=True, help_text='Detailed feedback and suggestions')),
                ('methodology_score', models.IntegerField(blank=True, help_text='Methodology quality (1-5)', null=True)),
                ('clarity_score', models.IntegerField(blank=True, help_text='Clarity and presentation (1-5)', null=True)),
                ('significance_score', models.IntegerField(blank=True, help_text='Scientific significance (1-5)', null=True)),
                ('overall_score', models.IntegerField(blank=True, help_text='Overall quality (1-5)', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('team_invitation', 'Team Invitation'), ('project_shared', 'Project Shared'), ('comment_reply', 'Comment Reply'), ('review_request', 'Review Request'), ('review_completed', 'Review Completed'), ('mention', 'Mentioned'), ('deadline_reminder', 'Deadline Reminder'), ('system', 'System Notification')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action_url', models.URLField(blank=True, help_text='URL for notification action')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('comment_type', models.CharField(choices=[('general', 'General Comment'), ('suggestion', 'Suggestion'), ('review', 'Review Comment'), ('question', 'Question'), ('approval', 'Approval'), ('concern', 'Concern')], default='general', max_length=20)),
                ('content', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='collaboration_app.comment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborativeEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('edit_type', models.CharField(choices=[('document', 'Document Edit'), ('code', 'Code Edit'), ('manuscript', 'Manuscript Edit'), ('data', 'Data Edit')], default='document', max_length=20)),
                ('field_name', models.CharField(help_text='Field being edited', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value')),
                ('new_value', models.TextField(blank=True, help_text='New value')),
                ('change_summary', models.CharField(blank=True, max_length=255)),
                ('is_minor', models.BooleanField(default=False, help_text='Minor edit (e.g., typo fix)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('team_created', 'Team Created'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('project_shared', 'Project Shared'), ('project_created', 'Project Created'), ('document_created', 'Document Created'), ('document_updated', 'Document Updated'), ('comment_added', 'Comment Added'), ('review_requested', 'Review Requested'), ('review_completed', 'Review Completed'), ('file_uploaded', 'File Uploaded'), ('milestone_reached', 'Milestone Reached')], max_length=30)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='collaboration_app.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('contributor', 'Contributor'), ('editor', 'Editor'), ('reviewer', 'Reviewer'), ('guest', 'Guest')], default='member', max_length=20)),
                ('can_invite_members', models.BooleanField(default=False)),
                ('can_create_projects', models.BooleanField(default=True)),
                ('can_manage_projects', models.BooleanField(default=False)),
                ('can_review_work', models.BooleanField(default=False)),
                ('can_export_data', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_team_invitations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='collaboration_app.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('member', 'Member'), ('contributor', 'Contributor'), ('editor', 'Editor'), ('reviewer', 'Reviewer'), ('guest', 'Guest')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Personal message with invitation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='collaboration_app.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='collaborati_email_193fa4_idx'), models.Index(fields=['team', 'status'], name='collaborati_team_id_148a81_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['owner', 'is_active'], name='collaborati_owner_i_ac9527_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['team_type', 'visibility'], name='collaborati_team_ty_e3d7ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sharedproject',
            unique_together={('project', 'team')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', 'status'], name='collaborati_reviewe_cb2746_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['content_type', 'object_id'], name='collaborati_content_9e9eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='collaborati_recipie_c377e1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='collaborati_recipie_1e007b_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id'], name='collaborati_content_2f8122_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'created_at'], name='collaborati_author__a931f4_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativeedit',
            index=models.Index(fields=['content_type', 'object_id'], name='collaborati_content_b50c08_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativeedit',
            index=models.Index(fields=['user', 'created_at'], name='collaborati_user_id_aef00d_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['team', 'created_at'], name='collaborati_team_id_c6e00e_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['actor', 'created_at'], name='collaborati_actor_i_5e70a2_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['activity_type', 'created_at'], name='collaborati_activit_da27b8_idx'),
        ),
    ]
