# Generated by Django 4.2.11 on 2025-06-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration_app', '0001_initial'),
    ]

    operations = [
    ]
