# Generated by Django 4.2.11 on 2025-06-27 16:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('orcid', models.CharField(blank=True, db_index=True, max_length=19)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('affiliation', models.CharField(blank=True, max_length=500)),
                ('h_index', models.IntegerField(blank=True, null=True)),
                ('total_citations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AuthorPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_order', models.IntegerField(default=1)),
                ('is_corresponding', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['author_order'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('citation_context', models.TextField(blank=True)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#1a2332', help_text='Hex color code for collection', max_length=7)),
                ('icon', models.CharField(default='fas fa-folder', help_text='FontAwesome icon class', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='Allow others to see this collection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=100)),
                ('issn', models.CharField(blank=True, db_index=True, max_length=9)),
                ('eissn', models.CharField(blank=True, max_length=9)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('website', models.URLField(blank=True)),
                ('open_access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('filter_type', models.CharField(choices=[('date_range', 'Date Range'), ('author', 'Author'), ('journal', 'Journal'), ('topic', 'Topic'), ('citation_count', 'Citation Count'), ('document_type', 'Document Type'), ('open_access', 'Open Access'), ('language', 'Language')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['filter_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(db_index=True)),
                ('abstract', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('article', 'Journal Article'), ('preprint', 'Preprint'), ('book', 'Book'), ('chapter', 'Book Chapter'), ('conference', 'Conference Paper'), ('thesis', 'Thesis/Dissertation'), ('report', 'Technical Report'), ('dataset', 'Dataset')], default='article', max_length=20)),
                ('publication_date', models.DateField(blank=True, db_index=True, null=True)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('pmid', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('arxiv_id', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('source', models.CharField(choices=[('pubmed', 'PubMed'), ('arxiv', 'arXiv'), ('doi', 'DOI'), ('google_scholar', 'Google Scholar'), ('internal', 'Internal'), ('manual', 'Manual Entry')], default='manual', max_length=20)),
                ('external_url', models.URLField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='scholar/pdfs/')),
                ('bibtex_file', models.FileField(blank=True, null=True, upload_to='scholar/bibtex/')),
                ('bibtex_content', models.TextField(blank=True, help_text='BibTeX citation content')),
                ('keywords', models.TextField(blank=True)),
                ('citation_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('retracted', 'Retracted'), ('pending', 'Pending Review')], default='active', max_length=20)),
                ('is_open_access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(through='scholar.AuthorPaper', to='scholar.author')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholar.journal')),
            ],
            options={
                'ordering': ['-publication_date', '-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('search_type', models.CharField(choices=[('simple', 'Simple Search'), ('advanced', 'Advanced Search'), ('author', 'Author Search'), ('citation', 'Citation Search'), ('semantic', 'Semantic Search')], default='simple', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('result_count', models.IntegerField(default=0)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.CharField(blank=True, help_text='Project name for organization', max_length=200)),
                ('personal_pdf', models.FileField(blank=True, null=True, upload_to='user_library/pdfs/')),
                ('personal_bibtex', models.FileField(blank=True, null=True, upload_to='user_library/bibtex/')),
                ('personal_notes', models.TextField(blank=True, help_text='Personal notes about this paper')),
                ('tags', models.CharField(blank=True, help_text='Personal tags, comma-separated', max_length=500)),
                ('reading_status', models.CharField(choices=[('to_read', 'To Read'), ('reading', 'Currently Reading'), ('read', 'Completed'), ('referenced', 'For Reference'), ('favorite', 'Favorite')], default='to_read', max_length=20)),
                ('importance_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('exported_count', models.IntegerField(default=0, help_text='Number of times this paper was exported')),
                ('last_exported', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collections', models.ManyToManyField(blank=True, related_name='library_papers', to='scholar.collection')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='scholar.searchindex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('paper_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='scholar.topic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('score', models.FloatField()),
                ('snippet', models.TextField(blank=True)),
                ('clicked', models.BooleanField(default=False)),
                ('click_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar.searchindex')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scholar.searchquery')),
            ],
            options={
                'ordering': ['search_query', 'rank'],
            },
        ),
        migrations.AddField(
            model_name='searchindex',
            name='topics',
            field=models.ManyToManyField(blank=True, to='scholar.topic'),
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('query_text', models.TextField()),
                ('search_type', models.CharField(choices=[('simple', 'Simple Search'), ('advanced', 'Advanced Search'), ('author', 'Author Search'), ('citation', 'Citation Search'), ('semantic', 'Semantic Search')], max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('email_alerts', models.BooleanField(default=False)),
                ('alert_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='never', max_length=10)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('similar', 'Similar Papers'), ('author_based', 'Based on Author'), ('citation_based', 'Based on Citations'), ('topic_based', 'Based on Topics'), ('collaborative', 'Collaborative Filtering'), ('trending', 'Trending Papers')], max_length=20)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reason', models.TextField(blank=True)),
                ('clicked', models.BooleanField(default=False)),
                ('feedback', models.CharField(blank=True, choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('neutral', 'Neutral')], max_length=20)),
                ('feedback_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interacted_at', models.DateTimeField(blank=True, null=True)),
                ('recommended_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_as', to='scholar.searchindex')),
                ('source_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_source', to='scholar.searchindex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('bibtex', 'BibTeX'), ('endnote', 'EndNote'), ('ris', 'RIS'), ('csv', 'CSV'), ('json', 'JSON'), ('pdf_bundle', 'PDF Bundle')], max_length=20)),
                ('paper_count', models.IntegerField()),
                ('collection_name', models.CharField(blank=True, help_text='Collection name if exported', max_length=200)),
                ('filter_criteria', models.JSONField(blank=True, default=dict, help_text='Applied filters during export')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['issn'], name='scholar_jou_issn_9bffbf_idx'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citation',
            name='cited_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_received', to='scholar.searchindex'),
        ),
        migrations.AddField(
            model_name='citation',
            name='citing_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_made', to='scholar.searchindex'),
        ),
        migrations.AddField(
            model_name='authorpaper',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar.author'),
        ),
        migrations.AddField(
            model_name='authorpaper',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar.searchindex'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['last_name', 'first_name'], name='scholar_aut_last_na_68075c_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['orcid'], name='scholar_aut_orcid_110a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['user', '-saved_at'], name='scholar_use_user_id_d3f320_idx'),
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['project'], name='scholar_use_project_3a690e_idx'),
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['reading_status'], name='scholar_use_reading_1cf3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['importance_rating'], name='scholar_use_importa_e17a9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlibrary',
            unique_together={('user', 'paper')},
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['name'], name='scholar_top_name_d0740e_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['search_query', 'rank'], name='scholar_sea_search__72493b_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['-created_at'], name='scholar_sea_created_e63aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['user', '-created_at'], name='scholar_sea_user_id_f4b494_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['publication_date', 'relevance_score'], name='scholar_sea_publica_4bf02d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['doi'], name='scholar_sea_doi_698562_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['pmid'], name='scholar_sea_pmid_d8d18e_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['arxiv_id'], name='scholar_sea_arxiv_i_f84b41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedsearch',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['user', '-created_at'], name='scholar_rec_user_id_2c6750_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['recommendation_type', '-score'], name='scholar_rec_recomme_0d7636_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryexport',
            index=models.Index(fields=['user', '-created_at'], name='scholar_lib_user_id_4e5d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryexport',
            index=models.Index(fields=['export_format'], name='scholar_lib_export__8db379_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', 'name'], name='scholar_col_user_id_39002d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='citation',
            index=models.Index(fields=['citing_paper', 'cited_paper'], name='scholar_cit_citing__17cbcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together={('citing_paper', 'cited_paper')},
        ),
        migrations.AlterUniqueTogether(
            name='authorpaper',
            unique_together={('author', 'paper')},
        ),
    ]
