# Generated by Django 4.2.11 on 2025-06-27 16:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colors', models.JSONField()),
                ('is_public', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_schemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('layout_type', models.CharField(default='grid', max_length=20)),
                ('layout_config', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('password_protected', models.BooleanField(default=False)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('theme', models.CharField(default='light', max_length=50)),
                ('custom_css', models.TextField(blank=True)),
                ('auto_refresh', models.BooleanField(default=False)),
                ('refresh_interval', models.IntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('file', 'File Upload'), ('database', 'Database Connection'), ('api', 'API Endpoint'), ('realtime', 'Real-time Stream'), ('computed', 'Computed/Derived')], max_length=20)),
                ('connection_config', models.JSONField()),
                ('schema', models.JSONField(blank=True, null=True)),
                ('refresh_interval', models.IntegerField(blank=True, help_text='Refresh interval in seconds', null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('updating', 'Updating'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('data', models.JSONField(blank=True, null=True)),
                ('configuration', models.JSONField(default=dict)),
                ('layout', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('is_interactive', models.BooleanField(default=True)),
                ('allow_download', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('view_count', models.IntegerField(default=0)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('color_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viz_app.colorscheme')),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viz_app.datasource')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to=settings.AUTH_USER_MODEL)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viz_app.visualization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('basic', 'Basic Charts'), ('statistical', 'Statistical Plots'), ('scientific', 'Scientific Visualization'), ('3d', '3D Visualization'), ('network', 'Network Graphs'), ('temporal', 'Time Series'), ('geospatial', 'Geospatial')], max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('default_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='VisualizationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('configuration', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viz_templates', to=settings.AUTH_USER_MODEL)),
                ('visualization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viz_app.visualizationtype')),
            ],
            options={
                'ordering': ['-usage_count', '-created_at'],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='VisualizationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('annotation_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='viz_app.visualizationcomment')),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='viz_app.visualization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='visualization',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viz_app.visualizationtemplate'),
        ),
        migrations.AddField(
            model_name='visualization',
            name='visualization_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viz_app.visualizationtype'),
        ),
        migrations.CreateModel(
            name='InteractiveElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('filter', 'Filter'), ('slider', 'Slider'), ('dropdown', 'Dropdown'), ('button', 'Button'), ('tooltip', 'Tooltip'), ('zoom', 'Zoom Control'), ('pan', 'Pan Control')], max_length=20)),
                ('element_id', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('configuration', models.JSONField()),
                ('target_data', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_elements', to='viz_app.visualization')),
            ],
            options={
                'ordering': ['order', 'element_id'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('png', 'PNG Image'), ('svg', 'SVG Vector'), ('pdf', 'PDF Document'), ('html', 'Interactive HTML'), ('json', 'JSON Data'), ('csv', 'CSV Data')], max_length=10)),
                ('options', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='viz_app.visualization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('height', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('order', models.IntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viz_app.dashboard')),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viz_app.visualization')),
            ],
            options={
                'ordering': ['order', 'position_y', 'position_x'],
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='visualizations',
            field=models.ManyToManyField(through='viz_app.DashboardVisualization', to='viz_app.visualization'),
        ),
        migrations.CreateModel(
            name='ChartConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis_label', models.CharField(blank=True, max_length=200)),
                ('y_axis_label', models.CharField(blank=True, max_length=200)),
                ('z_axis_label', models.CharField(blank=True, max_length=200)),
                ('x_axis_type', models.CharField(default='linear', max_length=20)),
                ('y_axis_type', models.CharField(default='linear', max_length=20)),
                ('show_grid', models.BooleanField(default=True)),
                ('show_legend', models.BooleanField(default=True)),
                ('legend_position', models.CharField(default='right', max_length=20)),
                ('error_bars', models.JSONField(blank=True, null=True)),
                ('confidence_intervals', models.JSONField(blank=True, null=True)),
                ('regression_lines', models.JSONField(blank=True, null=True)),
                ('annotations', models.JSONField(default=list)),
                ('custom_script', models.TextField(blank=True)),
                ('plugins', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visualization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chart_config', to='viz_app.visualization')),
            ],
        ),
        migrations.CreateModel(
            name='VisualizationShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('comment', 'View and Comment'), ('edit', 'Edit')], default='view', max_length=10)),
                ('share_token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('accessed', models.BooleanField(default=False)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_visualizations', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_visualizations', to=settings.AUTH_USER_MODEL)),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='viz_app.visualization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('visualization', 'shared_with', 'email')},
            },
        ),
        migrations.CreateModel(
            name='VisualizationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('unique_viewers', models.IntegerField(default=0)),
                ('exports', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('avg_view_duration', models.FloatField(default=0)),
                ('interactions', models.JSONField(default=dict)),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='viz_app.visualization')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['visualization', 'date'], name='viz_app_vis_visuali_bc0f34_idx')],
                'unique_together': {('visualization', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='visualization',
            index=models.Index(fields=['owner', 'status'], name='viz_app_vis_owner_i_46cb6a_idx'),
        ),
        migrations.AddIndex(
            model_name='visualization',
            index=models.Index(fields=['is_public', 'status'], name='viz_app_vis_is_publ_bb3e71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interactiveelement',
            unique_together={('visualization', 'element_id')},
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['user', 'status'], name='viz_app_exp_user_id_f7e2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['status', 'created_at'], name='viz_app_exp_status_681b09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardvisualization',
            unique_together={('dashboard', 'visualization')},
        ),
        migrations.AlterUniqueTogether(
            name='colorscheme',
            unique_together={('name', 'owner')},
        ),
    ]
