# Generated by Django 5.2.7 on 2025-10-22 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tier name (e.g., 'Bronze Supporter')", max_length=100
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum donation amount for this tier",
                        max_digits=10,
                    ),
                ),
                ("description", models.TextField(help_text="Description of the tier")),
                (
                    "benefits",
                    models.TextField(
                        help_text="Benefits provided to donors in this tier"
                    ),
                ),
                (
                    "badge_color",
                    models.CharField(
                        default="#4a6baf",
                        help_text="Hex color code for badge (e.g., #4a6baf)",
                        max_length=7,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this tier is currently offered"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order for displaying tiers"
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation Tier",
                "verbose_name_plural": "Donation Tiers",
                "ordering": ["display_order", "minimum_amount"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(max_length=255)),
                ("donor_email", models.EmailField(max_length=254)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("paypal", "PayPal"),
                            ("github", "GitHub Sponsors"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=255)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Show donation publicly on supporters page",
                    ),
                ),
                (
                    "is_visitor",
                    models.BooleanField(
                        default=False, help_text="Hide donor name if public"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional message from donor"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation",
                "verbose_name_plural": "Donations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="sustainabil_created_d38e8c_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="sustainabil_status_6e8ebe_idx",
                    ),
                ],
            },
        ),
    ]
