# Generated by Django 5.2.7 on 2025-10-22 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donations_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="donation",
            new_name="donations_a_created_888334_idx",
            old_name="sustainabil_created_d38e8c_idx",
        ),
        migrations.RenameIndex(
            model_name="donation",
            new_name="donations_a_status_7ad9c7_idx",
            old_name="sustainabil_status_6e8ebe_idx",
        ),
    ]
