# Generated by Django 4.2.11 on 2025-10-15 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("student", "Student (Undergraduate/Graduate)"),
                            ("researcher", "Researcher/Postdoc"),
                            ("professor", "Professor/Faculty"),
                            ("industry", "Industry Professional"),
                            ("independent", "Independent Researcher"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "research_field",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("computer_science", "Computer Science"),
                            ("biology", "Biology & Life Sciences"),
                            ("physics", "Physics"),
                            ("chemistry", "Chemistry"),
                            ("mathematics", "Mathematics"),
                            ("engineering", "Engineering"),
                            ("medicine", "Medicine & Health"),
                            ("social_sciences", "Social Sciences"),
                            ("humanities", "Humanities"),
                            ("earth_sciences", "Earth Sciences"),
                            ("psychology", "Psychology"),
                            ("neuroscience", "Neuroscience"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "is_academic_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Email verified as academic institution",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("weekly_digest", models.BooleanField(default=True)),
                ("profile_completed", models.BooleanField(default=False)),
                (
                    "profile_completion_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("total_login_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_email_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification",
                "verbose_name_plural": "Email Verifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
