# Generated by Django 5.2.7 on 2025-10-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="code_theme_dark",
            field=models.CharField(
                default="dracula",
                help_text="Code highlighting theme for dark mode",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="code_theme_light",
            field=models.CharField(
                default="atom-one-light",
                help_text="Code highlighting theme for light mode",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="dark",
                help_text="Site theme preference (light/dark)",
                max_length=10,
            ),
        ),
    ]
