# Generated by Django 5.2.7 on 2025-10-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0002_userprofile_code_theme_dark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="editor_theme_dark",
            field=models.CharField(
                default="nord",
                help_text="Editor theme for dark mode (CodeMirror)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="editor_theme_light",
            field=models.CharField(
                default="neat",
                help_text="Editor theme for light mode (CodeMirror)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="code_theme_dark",
            field=models.CharField(
                default="nord",
                help_text="Code highlighting theme for dark mode",
                max_length=50,
            ),
        ),
    ]
