# Generated by Django 4.2.11 on 2025-10-15 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArxivAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arxiv_username", models.CharField(max_length=200)),
                ("arxiv_password", models.CharField(max_length=500)),
                ("arxiv_email", models.EmailField(max_length=254)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_token", models.CharField(blank=True, max_length=255)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("orcid_id", models.CharField(blank=True, max_length=50)),
                ("affiliation", models.CharField(blank=True, max_length=500)),
                ("daily_submission_limit", models.IntegerField(default=5)),
                ("submissions_today", models.IntegerField(default=0)),
                ("last_submission_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("suspension_reason", models.TextField(blank=True)),
                ("suspended_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arxiv_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArxivCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("submission_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="writer_app.arxivcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "arXiv Categories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ArxivSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("arxiv_id", models.CharField(blank=True, max_length=50)),
                ("arxiv_url", models.URLField(blank=True)),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("new", "New Submission"),
                            ("replacement", "Replacement"),
                            ("withdrawal", "Withdrawal"),
                            ("cross_list", "Cross-list"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validating", "Validating"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("replaced", "Replaced"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("abstract", models.TextField()),
                ("authors", models.TextField()),
                (
                    "latex_source",
                    models.FileField(
                        blank=True, null=True, upload_to="arxiv_submissions/latex/"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="arxiv_submissions/pdfs/"
                    ),
                ),
                ("supplementary_files", models.JSONField(default=list)),
                ("comments", models.TextField(blank=True)),
                ("journal_reference", models.CharField(blank=True, max_length=500)),
                ("doi", models.CharField(blank=True, max_length=100)),
                ("arxiv_comments", models.TextField(blank=True)),
                ("moderation_reason", models.TextField(blank=True)),
                ("version", models.IntegerField(default=1)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_status_check", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("is_test_submission", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "arxiv_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="writer_app.arxivaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollaborativeSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("locked_sections", models.JSONField(blank=True, default=list)),
                ("cursor_position", models.JSONField(blank=True, default=dict)),
                ("characters_typed", models.IntegerField(default=0)),
                ("operations_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("article", "Journal Article"),
                            ("conference", "Conference Paper"),
                            ("thesis", "Thesis/Dissertation"),
                            ("report", "Technical Report"),
                            ("book", "Book/Chapter"),
                            ("preprint", "Preprint"),
                            ("custom", "Custom Template"),
                        ],
                        max_length=20,
                    ),
                ),
                ("journal_name", models.CharField(blank=True, max_length=200)),
                ("latex_template", models.TextField()),
                ("style_file", models.TextField(blank=True)),
                (
                    "bibliography_style",
                    models.CharField(default="plain", max_length=50),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="doc_templates/"
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doc_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="Manuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=500, unique=True)),
                ("abstract", models.TextField(blank=True)),
                ("keywords", models.CharField(blank=True, max_length=500)),
                ("content", models.TextField()),
                (
                    "compiled_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="manuscripts/pdfs/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("revision", "In Revision"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("target_journal", models.CharField(blank=True, max_length=200)),
                ("submission_deadline", models.DateField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                ("is_public", models.BooleanField(default=False)),
                ("is_modular", models.BooleanField(default=False)),
                ("paper_directory", models.CharField(blank=True, max_length=500)),
                ("word_count_abstract", models.IntegerField(default=0)),
                ("word_count_introduction", models.IntegerField(default=0)),
                ("word_count_methods", models.IntegerField(default=0)),
                ("word_count_results", models.IntegerField(default=0)),
                ("word_count_discussion", models.IntegerField(default=0)),
                ("word_count_total", models.IntegerField(default=0)),
                ("citation_count", models.IntegerField(default=0)),
                ("unique_citation_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_compiled", models.DateTimeField(blank=True, null=True)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_manuscripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manuscripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="writer_manuscripts",
                        to="project_app.project",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="writer_app.documenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    ("can_compile_manuscript", "Can compile manuscript"),
                    ("can_share_manuscript", "Can share manuscript"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ManuscriptBranch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_merged", models.BooleanField(default=False)),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("total_commits", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="ManuscriptSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("abstract", "Abstract"),
                            ("introduction", "Introduction"),
                            ("methods", "Methods"),
                            ("results", "Results"),
                            ("discussion", "Discussion"),
                            ("conclusion", "Conclusion"),
                            ("references", "References"),
                            ("appendix", "Appendix"),
                            ("custom", "Custom Section"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("improvement_suggestions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="writer_app.manuscript",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("manuscript", "order")},
            },
        ),
        migrations.CreateModel(
            name="ManuscriptVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.CharField(max_length=20)),
                ("version_tag", models.CharField(blank=True, max_length=100)),
                ("branch_name", models.CharField(default="main", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("commit_message", models.TextField(blank=True)),
                ("manuscript_data", models.JSONField()),
                ("section_contents", models.JSONField()),
                ("is_major_version", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("total_changes", models.IntegerField(default=0)),
                ("word_count_delta", models.IntegerField(default=0)),
                ("lines_added", models.IntegerField(default=0)),
                ("lines_removed", models.IntegerField(default=0)),
                (
                    "version_file",
                    models.FileField(
                        blank=True, null=True, upload_to="manuscript_versions/"
                    ),
                ),
                (
                    "diff_file",
                    models.FileField(
                        blank=True, null=True, upload_to="manuscript_diffs/"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="writer_app.manuscript",
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="writer_app.manuscriptversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("manuscript", "version_number", "branch_name")},
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("caption", models.TextField()),
                ("content", models.TextField()),
                (
                    "data_file",
                    models.FileField(
                        blank=True, null=True, upload_to="manuscripts/tables/"
                    ),
                ),
                ("position", models.CharField(default="htbp", max_length=10)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="writer_app.manuscript",
                    ),
                ),
                (
                    "referenced_in_sections",
                    models.ManyToManyField(
                        blank=True, to="writer_app.manuscriptsection"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MergeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("review", "In Review"),
                            ("approved", "Approved"),
                            ("merged", "Merged"),
                            ("closed", "Closed"),
                            ("draft", "Draft"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("has_conflicts", models.BooleanField(default=False)),
                ("conflict_data", models.JSONField(default=dict)),
                ("auto_mergeable", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="approved_merge_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_merge_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_requests",
                        to="writer_app.manuscript",
                    ),
                ),
                (
                    "merge_commit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_commit_for",
                        to="writer_app.manuscriptversion",
                    ),
                ),
                (
                    "merged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="merge_requests_to_review",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_requests_from",
                        to="writer_app.manuscriptbranch",
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_requests_from_version",
                        to="writer_app.manuscriptversion",
                    ),
                ),
                (
                    "target_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_requests_to",
                        to="writer_app.manuscriptbranch",
                    ),
                ),
                (
                    "target_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_requests_to_version",
                        to="writer_app.manuscriptversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="manuscriptbranch",
            name="base_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branched_from",
                to="writer_app.manuscriptversion",
            ),
        ),
        migrations.AddField(
            model_name="manuscriptbranch",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                related_name="contributed_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="manuscriptbranch",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="manuscriptbranch",
            name="manuscript",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="writer_app.manuscript",
            ),
        ),
        migrations.AddField(
            model_name="manuscriptbranch",
            name="merged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="manuscriptbranch",
            name="parent_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_branches",
                to="writer_app.manuscriptbranch",
            ),
        ),
        migrations.CreateModel(
            name="Figure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("caption", models.TextField()),
                ("file", models.ImageField(upload_to="manuscripts/figures/")),
                ("position", models.CharField(default="htbp", max_length=10)),
                ("width", models.FloatField(default=1.0)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="figures",
                        to="writer_app.manuscript",
                    ),
                ),
                (
                    "referenced_in_sections",
                    models.ManyToManyField(
                        blank=True, to="writer_app.manuscriptsection"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("insert", "Text Insertion"),
                            ("delete", "Text Deletion"),
                            ("replace", "Text Replacement"),
                            ("format", "Formatting Change"),
                        ],
                        max_length=20,
                    ),
                ),
                ("operation_data", models.JSONField()),
                ("content_before", models.TextField(blank=True)),
                ("content_after", models.TextField(blank=True)),
                ("version_number", models.IntegerField(default=1)),
                ("transform_applied", models.BooleanField(default=False)),
                ("conflict_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_changes",
                        to="writer_app.manuscript",
                    ),
                ),
                (
                    "parent_change",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="writer_app.documentchange",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="writer_app.manuscriptsection",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="writer_app.collaborativesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompilationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "compilation_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Compilation"),
                            ("draft", "Draft Mode"),
                            ("quick", "Quick Preview"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "output_pdf",
                    models.FileField(blank=True, null=True, upload_to="compilations/"),
                ),
                ("output_path", models.CharField(blank=True, max_length=500)),
                ("log_file", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_log", models.TextField(blank=True)),
                ("compilation_time", models.FloatField(blank=True, null=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compilation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compilation_jobs",
                        to="writer_app.manuscript",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="collaborativesession",
            name="manuscript",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborative_sessions",
                to="writer_app.manuscript",
            ),
        ),
        migrations.AddField(
            model_name="collaborativesession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="writing_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ArxivValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("overall_score", models.FloatField(default=0.0)),
                (
                    "latex_compilation",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "pdf_generation",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "metadata_validation",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "category_validation",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file_format_check",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("validation_details", models.JSONField(default=dict)),
                ("error_messages", models.JSONField(default=list)),
                ("warning_messages", models.JSONField(default=list)),
                ("latex_log", models.TextField(blank=True)),
                ("bibtex_issues", models.JSONField(default=list)),
                ("missing_figures", models.JSONField(default=list)),
                ("title_length_check", models.BooleanField(default=False)),
                ("abstract_length_check", models.BooleanField(default=False)),
                ("author_format_check", models.BooleanField(default=False)),
                ("total_file_size", models.FloatField(default=0.0)),
                ("max_file_size_exceeded", models.BooleanField(default=False)),
                ("unsupported_files", models.JSONField(default=list)),
                ("validation_started", models.DateTimeField(auto_now_add=True)),
                ("validation_completed", models.DateTimeField(blank=True, null=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="writer_app.arxivsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-validation_started"],
            },
        ),
        migrations.CreateModel(
            name="ArxivSubmissionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("change_reason", models.TextField(blank=True)),
                ("arxiv_response", models.JSONField(default=dict)),
                ("error_details", models.TextField(blank=True)),
                ("is_automatic", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="writer_app.arxivsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "arXiv Submission Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="arxivsubmission",
            name="manuscript",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arxiv_submissions",
                to="writer_app.manuscript",
            ),
        ),
        migrations.AddField(
            model_name="arxivsubmission",
            name="primary_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_submissions",
                to="writer_app.arxivcategory",
            ),
        ),
        migrations.AddField(
            model_name="arxivsubmission",
            name="replaces_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replacements",
                to="writer_app.arxivsubmission",
            ),
        ),
        migrations.AddField(
            model_name="arxivsubmission",
            name="secondary_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="secondary_submissions",
                to="writer_app.arxivcategory",
            ),
        ),
        migrations.AddField(
            model_name="arxivsubmission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arxiv_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ArxivApiResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_endpoint", models.CharField(max_length=200)),
                ("request_method", models.CharField(max_length=10)),
                ("request_data", models.JSONField(default=dict)),
                ("response_status", models.IntegerField()),
                ("response_data", models.JSONField(default=dict)),
                ("response_headers", models.JSONField(default=dict)),
                ("request_time", models.DateTimeField()),
                ("response_time", models.DateTimeField()),
                ("duration_ms", models.IntegerField()),
                ("is_error", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_responses",
                        to="writer_app.arxivsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIAssistanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assistance_type",
                    models.CharField(
                        choices=[
                            ("content", "Content Generation"),
                            ("revision", "Text Revision"),
                            ("citation", "Citation Suggestion"),
                            ("grammar", "Grammar Check"),
                            ("style", "Style Improvement"),
                            ("generate_section", "Section Generation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("section_type", models.CharField(blank=True, max_length=50)),
                ("prompt", models.TextField(blank=True)),
                ("original_text", models.TextField(blank=True)),
                ("suggested_text", models.TextField(blank=True)),
                ("generated_text", models.TextField(blank=True)),
                ("accepted", models.BooleanField(default=False)),
                ("target_section", models.CharField(blank=True, max_length=50)),
                ("word_count_target", models.IntegerField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_logs",
                        to="writer_app.manuscript",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="writer_app.manuscriptsection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="manuscriptbranch",
            unique_together={("manuscript", "name")},
        ),
        migrations.CreateModel(
            name="DiffResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "diff_type",
                    models.CharField(
                        choices=[
                            ("unified", "Unified Diff"),
                            ("side_by_side", "Side by Side"),
                            ("word_level", "Word Level"),
                            ("semantic", "Semantic Diff"),
                        ],
                        default="unified",
                        max_length=20,
                    ),
                ),
                ("diff_data", models.JSONField()),
                ("diff_html", models.TextField(blank=True)),
                ("diff_stats", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("is_cached", models.BooleanField(default=True)),
                ("cache_expires", models.DateTimeField(blank=True, null=True)),
                (
                    "from_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diffs_from",
                        to="writer_app.manuscriptversion",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diffs",
                        to="writer_app.manuscript",
                    ),
                ),
                (
                    "to_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diffs_to",
                        to="writer_app.manuscriptversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
                "unique_together": {("from_version", "to_version", "diff_type")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="collaborativesession",
            unique_together={("manuscript", "user", "session_id")},
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citation_key", models.CharField(max_length=100)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("article", "Journal Article"),
                            ("book", "Book"),
                            ("inproceedings", "Conference Paper"),
                            ("techreport", "Technical Report"),
                            ("phdthesis", "PhD Thesis"),
                            ("misc", "Miscellaneous"),
                        ],
                        max_length=20,
                    ),
                ),
                ("authors", models.TextField()),
                ("title", models.CharField(max_length=500)),
                ("year", models.IntegerField()),
                ("journal", models.CharField(blank=True, max_length=200)),
                ("volume", models.CharField(blank=True, max_length=20)),
                ("number", models.CharField(blank=True, max_length=20)),
                ("pages", models.CharField(blank=True, max_length=50)),
                ("doi", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True)),
                ("bibtex_entry", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cited_in_sections",
                    models.ManyToManyField(
                        blank=True, to="writer_app.manuscriptsection"
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="writer_app.manuscript",
                    ),
                ),
            ],
            options={
                "ordering": ["authors", "year"],
                "unique_together": {("manuscript", "citation_key")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="arxivsubmission",
            unique_together={("manuscript", "version")},
        ),
    ]
