# Generated by Django 4.2.11 on 2025-06-27 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('article', 'Journal Article'), ('conference', 'Conference Paper'), ('thesis', 'Thesis/Dissertation'), ('report', 'Technical Report'), ('book', 'Book/Chapter'), ('preprint', 'Preprint'), ('custom', 'Custom Template')], max_length=20)),
                ('journal_name', models.CharField(blank=True, max_length=200)),
                ('latex_template', models.TextField()),
                ('style_file', models.TextField(blank=True)),
                ('bibliography_style', models.CharField(default='plain', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='doc_templates/')),
                ('is_public', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('compiled_pdf', models.FileField(blank=True, null=True, upload_to='manuscripts/pdfs/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('revision', 'In Revision'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('target_journal', models.CharField(blank=True, max_length=200)),
                ('submission_deadline', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_public', models.BooleanField(default=False)),
                ('ai_suggestions_count', models.IntegerField(default=0)),
                ('last_ai_assist', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_compiled', models.DateTimeField(blank=True, null=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_manuscripts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscripts', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writer_app.documenttemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
                'permissions': [('can_compile_manuscript', 'Can compile manuscript'), ('can_share_manuscript', 'Can share manuscript')],
            },
        ),
        migrations.CreateModel(
            name='ManuscriptSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('abstract', 'Abstract'), ('introduction', 'Introduction'), ('methods', 'Methods'), ('results', 'Results'), ('discussion', 'Discussion'), ('conclusion', 'Conclusion'), ('references', 'References'), ('appendix', 'Appendix'), ('custom', 'Custom Section')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('ai_enhanced', models.BooleanField(default=False)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='writer_app.manuscript')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('manuscript', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('caption', models.TextField()),
                ('content', models.TextField()),
                ('data_file', models.FileField(blank=True, null=True, upload_to='manuscripts/tables/')),
                ('position', models.CharField(default='htbp', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='writer_app.manuscript')),
                ('referenced_in_sections', models.ManyToManyField(blank=True, to='writer_app.manuscriptsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('caption', models.TextField()),
                ('file', models.ImageField(upload_to='manuscripts/figures/')),
                ('position', models.CharField(default='htbp', max_length=10)),
                ('width', models.FloatField(default=1.0)),
                ('enhanced_file', models.ImageField(blank=True, null=True, upload_to='manuscripts/figures/enhanced/')),
                ('ai_caption', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='writer_app.manuscript')),
                ('referenced_in_sections', models.ManyToManyField(blank=True, to='writer_app.manuscriptsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompilationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('compilation_type', models.CharField(choices=[('full', 'Full Compilation'), ('draft', 'Draft Mode'), ('quick', 'Quick Preview')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('output_pdf', models.FileField(blank=True, null=True, upload_to='compilations/')),
                ('output_path', models.CharField(blank=True, max_length=500)),
                ('log_file', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_log', models.TextField(blank=True)),
                ('compilation_time', models.FloatField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compilation_jobs', to=settings.AUTH_USER_MODEL)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compilation_jobs', to='writer_app.manuscript')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAssistanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance_type', models.CharField(choices=[('content', 'Content Generation'), ('revision', 'Text Revision'), ('citation', 'Citation Suggestion'), ('figure', 'Figure Enhancement'), ('grammar', 'Grammar Check'), ('style', 'Style Improvement'), ('generate_section', 'Section Generation')], max_length=20)),
                ('section_type', models.CharField(blank=True, max_length=50)),
                ('prompt', models.TextField(blank=True)),
                ('original_text', models.TextField(blank=True)),
                ('suggested_text', models.TextField(blank=True)),
                ('generated_text', models.TextField(blank=True)),
                ('accepted', models.BooleanField(default=False)),
                ('tokens_used', models.IntegerField(default=0)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='writer_app.manuscript')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writer_app.manuscriptsection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_key', models.CharField(max_length=100)),
                ('entry_type', models.CharField(choices=[('article', 'Journal Article'), ('book', 'Book'), ('inproceedings', 'Conference Paper'), ('techreport', 'Technical Report'), ('phdthesis', 'PhD Thesis'), ('misc', 'Miscellaneous')], max_length=20)),
                ('authors', models.TextField()),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('journal', models.CharField(blank=True, max_length=200)),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('bibtex_entry', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cited_in_sections', models.ManyToManyField(blank=True, to='writer_app.manuscriptsection')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='writer_app.manuscript')),
            ],
            options={
                'ordering': ['authors', 'year'],
                'unique_together': {('manuscript', 'citation_key')},
            },
        ),
    ]
