# Generated by Django 4.2.11 on 2025-06-27 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_manuscript_project'),
        ('writer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistancelog',
            name='target_section',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aiassistancelog',
            name='word_count_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='citation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='is_modular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='paper_directory',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_manuscripts', to='core_app.project'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='unique_citation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='word_count_abstract',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='word_count_discussion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='word_count_introduction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='word_count_methods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='word_count_results',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='word_count_total',
            field=models.IntegerField(default=0),
        ),
    ]
