# Generated by Django 5.2.7 on 2025-11-16 23:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writer_app", "0004_aiassistancelog_arxivaccount_arxivcategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborativeEdit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section_id", models.CharField(max_length=100)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("insert", "Insert"),
                            ("delete", "Delete"),
                            ("retain", "Retain"),
                        ],
                        max_length=20,
                    ),
                ),
                ("operation_data", models.JSONField()),
                ("version", models.IntegerField()),
                ("client_version", models.IntegerField()),
                ("was_transformed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborative_edits",
                        to="writer_app.manuscript",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edits",
                        to="writer_app.collaborativesession",
                    ),
                ),
            ],
            options={
                "ordering": ["version"],
                "indexes": [
                    models.Index(
                        fields=["manuscript", "section_id", "version"],
                        name="writer_app__manuscr_98b4a0_idx",
                    ),
                    models.Index(
                        fields=["session", "created_at"],
                        name="writer_app__session_5175fe_idx",
                    ),
                ],
            },
        ),
    ]
