# Generated by Django 5.2.7 on 2025-11-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("writer_app", "0006_collaborationinvitation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collaborativeedit",
            name="manuscript",
        ),
        migrations.RemoveField(
            model_name="collaborativeedit",
            name="session",
        ),
        migrations.DeleteModel(
            name="CollaborationInvitation",
        ),
        migrations.DeleteModel(
            name="CollaborativeEdit",
        ),
    ]
