# Generated by Django 5.2.7 on 2025-10-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="user",
        ),
        migrations.DeleteModel(
            name="DonationTier",
        ),
        migrations.DeleteModel(
            name="Donation",
        ),
    ]
