# Generated by Django 5.2.7 on 2025-10-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_app", "0002_remove_duplicate_donation_models"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailVerification",
        ),
    ]
