# Generated by Django 5.2.7 on 2025-10-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_app", "0003_remove_emailverification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cloudresource",
            new_name="public_app__user_id_6cea62_idx",
            old_name="public_app_c_user_id_88f098_idx",
        ),
    ]
