# Generated by Django 5.2.7 on 2025-11-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "public_app",
            "0004_rename_public_app_c_user_id_88f098_idx_public_app__user_id_6cea62_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_username", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("avatar_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("creator", "Creator"),
                            ("maintainer", "Maintainer"),
                            ("core", "Core Team"),
                            ("contributor", "Contributor"),
                        ],
                        default="contributor",
                        max_length=20,
                    ),
                ),
                ("is_core_team", models.BooleanField(default=False)),
                ("contributions", models.IntegerField(default=0)),
                ("contributions_description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=1000)),
                ("first_contribution", models.DateTimeField(blank=True, null=True)),
                ("last_contribution", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-contributions", "-last_contribution"],
            },
        ),
    ]
