# Generated by Django 5.2.7 on 2025-11-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_app", "0005_contributor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "cpu_percent",
                    models.FloatField(help_text="CPU usage percentage (0-100)"),
                ),
                (
                    "cpu_cores",
                    models.IntegerField(
                        blank=True, help_text="Number of physical CPU cores", null=True
                    ),
                ),
                (
                    "cpu_cores_logical",
                    models.IntegerField(
                        blank=True, help_text="Number of logical CPU cores", null=True
                    ),
                ),
                (
                    "memory_percent",
                    models.FloatField(help_text="Memory usage percentage (0-100)"),
                ),
                ("memory_used_gb", models.FloatField(help_text="Memory used in GB")),
                ("memory_total_gb", models.FloatField(help_text="Total memory in GB")),
                (
                    "memory_available_gb",
                    models.FloatField(help_text="Available memory in GB"),
                ),
                (
                    "disk_percent",
                    models.FloatField(help_text="Disk usage percentage (0-100)"),
                ),
                ("disk_used_gb", models.FloatField(help_text="Disk space used in GB")),
                (
                    "disk_total_gb",
                    models.FloatField(help_text="Total disk space in GB"),
                ),
                (
                    "disk_read_mb",
                    models.FloatField(help_text="Total disk read in MB since boot"),
                ),
                (
                    "disk_write_mb",
                    models.FloatField(help_text="Total disk write in MB since boot"),
                ),
                (
                    "net_sent_mb",
                    models.FloatField(help_text="Total network sent in MB since boot"),
                ),
                (
                    "net_recv_mb",
                    models.FloatField(
                        help_text="Total network received in MB since boot"
                    ),
                ),
                (
                    "docker_services_running",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of running Docker services",
                        null=True,
                    ),
                ),
                (
                    "ssh_gateway_status",
                    models.BooleanField(
                        default=False, help_text="SSH gateway service status"
                    ),
                ),
                (
                    "gitea_ssh_status",
                    models.BooleanField(
                        default=False, help_text="Gitea SSH service status"
                    ),
                ),
                (
                    "database_status",
                    models.BooleanField(
                        default=False, help_text="Database connection status"
                    ),
                ),
                (
                    "redis_status",
                    models.BooleanField(default=False, help_text="Redis cache status"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Server Metric",
                "verbose_name_plural": "Server Metrics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="public_app__timesta_acbb32_idx"
                    )
                ],
            },
        ),
    ]
