# Generated by Django 5.2.7 on 2025-11-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_app", "0006_servermetrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="servermetrics",
            name="visitor_pool_allocated",
            field=models.IntegerField(
                blank=True, help_text="Number of allocated visitor slots", null=True
            ),
        ),
        migrations.AddField(
            model_name="servermetrics",
            name="visitor_pool_total",
            field=models.IntegerField(
                blank=True, help_text="Total visitor pool size", null=True
            ),
        ),
    ]
