# Generated by Django 5.2.7 on 2025-11-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_app", "0007_servermetrics_visitor_pool_allocated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servermetrics",
            name="active_users_count",
            field=models.IntegerField(
                blank=True, help_text="Number of currently logged-in users", null=True
            ),
        ),
    ]
