# Generated by Django 5.2.7 on 2025-11-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_app", "0008_servermetrics_active_users_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="servermetrics",
            name="gpu_percent",
            field=models.FloatField(
                blank=True, help_text="GPU usage percentage (0-100)", null=True
            ),
        ),
    ]
