# Generated by Django 4.2.11 on 2025-06-29 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_id', models.BigIntegerField(help_text='GitHub user ID', unique=True)),
                ('github_username', models.CharField(help_text='GitHub username', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, help_text='Full name', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Public email', max_length=254)),
                ('bio', models.TextField(blank=True, help_text='Profile bio')),
                ('blog', models.URLField(blank=True, help_text='Website/blog URL')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('public_repos', models.IntegerField(default=0, help_text='Number of public repositories')),
                ('public_gists', models.IntegerField(default=0, help_text='Number of public gists')),
                ('followers', models.IntegerField(default=0, help_text='Number of followers')),
                ('following', models.IntegerField(default=0, help_text='Number of following')),
                ('is_synced', models.BooleanField(default=False, help_text='Profile has been synced with GitHub')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_repositories', models.BooleanField(default=True, help_text='Auto-sync repositories from GitHub')),
                ('auto_sync_enabled', models.BooleanField(default=True, help_text='Enable automatic periodic sync')),
                ('public_profile', models.BooleanField(default=True, help_text='Make GitHub profile visible to other users')),
                ('show_repositories', models.BooleanField(default=True, help_text='Show GitHub repositories in Code module')),
                ('github_data', models.JSONField(blank=True, default=dict, help_text='Raw GitHub profile data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Profile',
                'verbose_name_plural': 'GitHub Profiles',
                'ordering': ['github_username'],
            },
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_id', models.BigIntegerField(help_text='GitHub repository ID')),
                ('name', models.CharField(help_text='Repository name', max_length=255)),
                ('full_name', models.CharField(help_text='Full repository name (owner/repo)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Repository description')),
                ('is_private', models.BooleanField(default=False, help_text='Repository is private')),
                ('is_fork', models.BooleanField(default=False, help_text='Repository is a fork')),
                ('is_archived', models.BooleanField(default=False, help_text='Repository is archived')),
                ('is_disabled', models.BooleanField(default=False, help_text='Repository is disabled')),
                ('default_branch', models.CharField(default='main', help_text='Default branch name', max_length=100)),
                ('language', models.CharField(blank=True, help_text='Primary language', max_length=50)),
                ('topics', models.JSONField(blank=True, default=list, help_text='Repository topics/tags')),
                ('size', models.IntegerField(default=0, help_text='Repository size in KB')),
                ('stargazers_count', models.IntegerField(default=0, help_text='Number of stars')),
                ('watchers_count', models.IntegerField(default=0, help_text='Number of watchers')),
                ('forks_count', models.IntegerField(default=0, help_text='Number of forks')),
                ('open_issues_count', models.IntegerField(default=0, help_text='Number of open issues')),
                ('clone_url', models.URLField(help_text='HTTPS clone URL')),
                ('ssh_url', models.CharField(help_text='SSH clone URL', max_length=255)),
                ('git_url', models.URLField(help_text='Git protocol URL')),
                ('github_created_at', models.DateTimeField(help_text='Repository creation date on GitHub')),
                ('github_updated_at', models.DateTimeField(help_text='Last update on GitHub')),
                ('github_pushed_at', models.DateTimeField(blank=True, help_text='Last push to GitHub', null=True)),
                ('is_connected', models.BooleanField(default=False, help_text='Connected to Code module')),
                ('auto_sync_enabled', models.BooleanField(default=True, help_text='Enable automatic sync')),
                ('sync_issues', models.BooleanField(default=False, help_text='Sync issues and pull requests')),
                ('sync_commits', models.BooleanField(default=True, help_text='Sync commit history')),
                ('github_data', models.JSONField(blank=True, default=dict, help_text='Raw GitHub repository data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_notebook', models.ForeignKey(blank=True, help_text='Linked Code notebook', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_repositories', to='code_app.notebook')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repositories', to='github_app.githubprofile')),
            ],
            options={
                'verbose_name': 'GitHub Repository',
                'verbose_name_plural': 'GitHub Repositories',
                'ordering': ['-github_updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GitHubOAuth2Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='GitHub access token', max_length=255)),
                ('token_type', models.CharField(default='bearer', max_length=50)),
                ('scope', models.CharField(help_text='OAuth scope granted', max_length=255)),
                ('github_username', models.CharField(help_text='GitHub username', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub OAuth2 Token',
                'verbose_name_plural': 'GitHub OAuth2 Tokens',
            },
        ),
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_direction', models.CharField(choices=[('github_to_code', 'GitHub → Code'), ('code_to_github', 'Code → GitHub'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=20)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Error'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('auto_sync_enabled', models.BooleanField(default=True, help_text='Enable automatic synchronization')),
                ('sync_branches', models.JSONField(blank=True, default=list, help_text='Branches to sync')),
                ('sync_files', models.JSONField(blank=True, default=list, help_text='File patterns to sync')),
                ('ignore_patterns', models.JSONField(blank=True, default=list, help_text='Patterns to ignore during sync')),
                ('webhook_url', models.URLField(blank=True, help_text='GitHub webhook URL')),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook secret for verification', max_length=255)),
                ('webhook_active', models.BooleanField(default=False, help_text='Webhook is active')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful sync', null=True)),
                ('last_sync_commit', models.CharField(blank=True, help_text='Last synced commit SHA', max_length=40)),
                ('last_error', models.TextField(blank=True, help_text='Last sync error message')),
                ('total_syncs', models.IntegerField(default=0, help_text='Total number of syncs performed')),
                ('successful_syncs', models.IntegerField(default=0, help_text='Number of successful syncs')),
                ('failed_syncs', models.IntegerField(default=0, help_text='Number of failed syncs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='github_app.githubrepository')),
            ],
            options={
                'verbose_name': 'GitHub Connection',
                'verbose_name_plural': 'GitHub Connections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_id', models.BigIntegerField(help_text='GitHub user ID')),
                ('github_username', models.CharField(help_text='GitHub username', max_length=100)),
                ('permission', models.CharField(choices=[('read', 'Read'), ('triage', 'Triage'), ('write', 'Write'), ('maintain', 'Maintain'), ('admin', 'Admin')], help_text='Permission level', max_length=20)),
                ('can_sync', models.BooleanField(default=False, help_text='Can sync repository to Code module')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Receive collaboration notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='github_app.githubrepository')),
                ('scitex_user', models.ForeignKey(blank=True, help_text='Connected SciTeX user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Collaborator',
                'verbose_name_plural': 'GitHub Collaborators',
                'ordering': ['github_username'],
            },
        ),
        migrations.CreateModel(
            name='GitHubSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('profile', 'Profile Sync'), ('repositories', 'Repositories Sync'), ('repository', 'Single Repository Sync'), ('code_sync', 'Code Synchronization'), ('webhook', 'Webhook Event'), ('full', 'Full Sync')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_created', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('items_deleted', models.IntegerField(default=0)),
                ('items_skipped', models.IntegerField(default=0)),
                ('sync_details', models.JSONField(blank=True, default=dict, help_text='Detailed sync information')),
                ('commits_synced', models.IntegerField(default=0, help_text='Number of commits synced')),
                ('files_synced', models.IntegerField(default=0, help_text='Number of files synced')),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='github_app.githubprofile')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='github_app.githubrepository')),
            ],
            options={
                'verbose_name': 'GitHub Sync Log',
                'verbose_name_plural': 'GitHub Sync Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['profile', '-started_at'], name='github_app__profile_ee42de_idx'), models.Index(fields=['repository', '-started_at'], name='github_app__reposit_d32c9c_idx'), models.Index(fields=['status'], name='github_app__status_aaff39_idx'), models.Index(fields=['sync_type'], name='github_app__sync_ty_e84151_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['profile', '-github_updated_at'], name='github_app__profile_cc7ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['github_id'], name='github_app__github__40ae02_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['full_name'], name='github_app__full_na_1ee8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['language'], name='github_app__languag_e01668_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['is_private'], name='github_app__is_priv_791e33_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['is_connected'], name='github_app__is_conn_f15069_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='githubrepository',
            unique_together={('profile', 'github_id')},
        ),
        migrations.AddIndex(
            model_name='githubprofile',
            index=models.Index(fields=['github_id'], name='github_app__github__10b705_idx'),
        ),
        migrations.AddIndex(
            model_name='githubprofile',
            index=models.Index(fields=['github_username'], name='github_app__github__9b756b_idx'),
        ),
        migrations.AddIndex(
            model_name='githubprofile',
            index=models.Index(fields=['user'], name='github_app__user_id_e0f873_idx'),
        ),
        migrations.AddIndex(
            model_name='githubprofile',
            index=models.Index(fields=['last_sync_at'], name='github_app__last_sy_39a150_idx'),
        ),
        migrations.AddIndex(
            model_name='githuboauth2token',
            index=models.Index(fields=['user'], name='github_app__user_id_f2ccf3_idx'),
        ),
        migrations.AddIndex(
            model_name='githuboauth2token',
            index=models.Index(fields=['github_username'], name='github_app__github__bca9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='githubconnection',
            index=models.Index(fields=['repository'], name='github_app__reposit_81f306_idx'),
        ),
        migrations.AddIndex(
            model_name='githubconnection',
            index=models.Index(fields=['sync_status'], name='github_app__sync_st_810f36_idx'),
        ),
        migrations.AddIndex(
            model_name='githubconnection',
            index=models.Index(fields=['last_sync_at'], name='github_app__last_sy_039487_idx'),
        ),
        migrations.AddIndex(
            model_name='githubconnection',
            index=models.Index(fields=['auto_sync_enabled'], name='github_app__auto_sy_0e1a45_idx'),
        ),
        migrations.AddIndex(
            model_name='githubcollaborator',
            index=models.Index(fields=['repository', 'permission'], name='github_app__reposit_bd9426_idx'),
        ),
        migrations.AddIndex(
            model_name='githubcollaborator',
            index=models.Index(fields=['github_username'], name='github_app__github__2b750b_idx'),
        ),
        migrations.AddIndex(
            model_name='githubcollaborator',
            index=models.Index(fields=['scitex_user'], name='github_app__scitex__7b9000_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='githubcollaborator',
            unique_together={('repository', 'github_id')},
        ),
    ]
