# Generated by Django 4.2.11 on 2025-10-15 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeExecutionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "execution_type",
                    models.CharField(
                        choices=[
                            ("script", "Python Script"),
                            ("notebook", "Jupyter Notebook"),
                            ("analysis", "Data Analysis"),
                            ("mngs", "MNGS Function Call"),
                        ],
                        default="script",
                        max_length=20,
                    ),
                ),
                ("source_code", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("output", models.TextField(blank=True)),
                ("error_output", models.TextField(blank=True)),
                ("return_code", models.IntegerField(blank=True, null=True)),
                ("cpu_time", models.FloatField(blank=True, null=True)),
                ("memory_peak", models.BigIntegerField(blank=True, null=True)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("timeout_seconds", models.IntegerField(default=300)),
                ("max_memory_mb", models.IntegerField(default=512)),
                ("max_cpu_time", models.IntegerField(default=180)),
                ("output_files", models.JSONField(default=list)),
                ("plot_files", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataAnalysisJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("time_series", "Time Series Analysis"),
                            ("statistics", "Statistical Analysis"),
                            ("signal_processing", "Signal Processing"),
                            ("machine_learning", "Machine Learning"),
                            ("visualization", "Data Visualization"),
                            ("custom", "Custom Analysis"),
                        ],
                        max_length=30,
                    ),
                ),
                ("input_data_path", models.CharField(blank=True, max_length=500)),
                ("parameters", models.JSONField(default=dict)),
                ("results", models.JSONField(default=dict)),
                ("summary", models.TextField(blank=True)),
                ("figures_generated", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code_job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="code_app.codeexecutionjob",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu_seconds", models.FloatField(default=0.0)),
                ("memory_mb_hours", models.FloatField(default=0.0)),
                ("storage_gb", models.FloatField(default=0.0)),
                ("network_gb", models.FloatField(default=0.0)),
                ("code_executions", models.IntegerField(default=0)),
                ("analysis_jobs", models.IntegerField(default=0)),
                ("notebook_runs", models.IntegerField(default=0)),
                ("date", models.DateField()),
                ("month", models.CharField(max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "month"], name="code_app_re_user_id_434016_idx"
                    ),
                    models.Index(fields=["date"], name="code_app_re_date_d156e2_idx"),
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="Notebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notebook_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("shared", "Shared"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("is_public", models.BooleanField(default=False)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                ("execution_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_notebooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "title")},
            },
        ),
        migrations.CreateModel(
            name="CodeLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("library_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "library_type",
                    models.CharField(
                        choices=[
                            ("function", "Function"),
                            ("class", "Class"),
                            ("script", "Script"),
                            ("template", "Template"),
                            ("example", "Example"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=200)),
                ("source_code", models.TextField()),
                ("language", models.CharField(default="python", max_length=20)),
                ("requirements", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_library",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="codeexecutionjob",
            index=models.Index(
                fields=["user", "status"], name="code_app_co_user_id_a8fbc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codeexecutionjob",
            index=models.Index(
                fields=["created_at"], name="code_app_co_created_7321f1_idx"
            ),
        ),
    ]
