# Generated by Django 5.2.7 on 2025-11-25 14:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_app", "0001_initial"),
        ("project_app", "0022_alter_visitorallocation_visitor_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("tensorboard", "TensorBoard"),
                            ("jupyter", "Jupyter Lab"),
                            ("mlflow", "MLflow"),
                            ("streamlit", "Streamlit"),
                            ("custom", "Custom Service"),
                        ],
                        max_length=50,
                    ),
                ),
                ("port", models.IntegerField()),
                ("process_id", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("starting", "Starting"),
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("error", "Error"),
                        ],
                        default="starting",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_accessed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="project_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="code_app_pr_project_f0648e_idx",
                    ),
                    models.Index(fields=["port"], name="code_app_pr_port_5d50ec_idx"),
                    models.Index(
                        fields=["last_accessed"], name="code_app_pr_last_ac_e1fc44_idx"
                    ),
                ],
            },
        ),
    ]
