# Generated by Django 5.2.7 on 2025-11-30 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_app", "0002_projectservice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slurm_max_concurrent_jobs",
                    models.IntegerField(blank=True, null=True),
                ),
                ("slurm_max_queued_jobs", models.IntegerField(blank=True, null=True)),
                (
                    "slurm_max_cpu_hours_daily",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "slurm_max_cpu_hours_monthly",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "slurm_max_memory_gb_per_job",
                    models.IntegerField(blank=True, null=True),
                ),
                ("slurm_max_runtime_hours", models.IntegerField(blank=True, null=True)),
                (
                    "slurm_allowed_partitions",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "celery_ai_calls_per_minute",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "celery_search_per_minute",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "celery_compute_per_minute",
                    models.IntegerField(blank=True, null=True),
                ),
                ("celery_pdf_per_hour", models.IntegerField(blank=True, null=True)),
                ("storage_total_gb", models.IntegerField(blank=True, null=True)),
                ("storage_project_max_gb", models.IntegerField(blank=True, null=True)),
                ("storage_file_upload_mb", models.IntegerField(blank=True, null=True)),
                ("max_projects", models.IntegerField(blank=True, null=True)),
                (
                    "max_collaborators_per_project",
                    models.IntegerField(blank=True, null=True),
                ),
                ("max_api_keys", models.IntegerField(blank=True, null=True)),
                (
                    "http_requests_per_minute",
                    models.IntegerField(blank=True, null=True),
                ),
                ("websocket_connections", models.IntegerField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about quota changes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Quota",
                "verbose_name_plural": "User Quotas",
            },
        ),
    ]
