# Generated by Django 4.2.11 on 2025-10-15 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(default="project", max_length=200, unique=True),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Project progress percentage (0-100)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "hypotheses",
                    models.TextField(help_text="Research hypotheses (required)"),
                ),
                (
                    "source_code_url",
                    models.URLField(
                        blank=True, help_text="GitHub/GitLab repository URL"
                    ),
                ),
                (
                    "data_location",
                    models.CharField(
                        blank=True,
                        help_text="Relative path to project directory",
                        max_length=500,
                    ),
                ),
                (
                    "github_token",
                    models.CharField(
                        blank=True, help_text="GitHub OAuth token", max_length=255
                    ),
                ),
                (
                    "github_repo_id",
                    models.IntegerField(
                        blank=True, help_text="GitHub repository ID", null=True
                    ),
                ),
                (
                    "github_repo_name",
                    models.CharField(
                        blank=True, help_text="GitHub repository name", max_length=200
                    ),
                ),
                (
                    "github_owner",
                    models.CharField(
                        blank=True, help_text="GitHub repository owner", max_length=100
                    ),
                ),
                (
                    "current_branch",
                    models.CharField(
                        default="main", help_text="Current git branch", max_length=100
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, help_text="Last GitHub sync timestamp", null=True
                    ),
                ),
                (
                    "github_integration_enabled",
                    models.BooleanField(
                        default=False, help_text="GitHub integration status"
                    ),
                ),
                (
                    "directory_created",
                    models.BooleanField(
                        default=False,
                        help_text="Whether project directory has been created",
                    ),
                ),
                (
                    "storage_used",
                    models.BigIntegerField(
                        default=0, help_text="Storage used by project in bytes"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, help_text="Last activity in project directory"
                    ),
                ),
                (
                    "search_completed",
                    models.BooleanField(
                        default=False, help_text="Literature search completed"
                    ),
                ),
                (
                    "knowledge_gap_identified",
                    models.TextField(blank=True, help_text="Identified knowledge gaps"),
                ),
                (
                    "analysis_completed",
                    models.BooleanField(
                        default=False, help_text="Code analysis completed"
                    ),
                ),
                (
                    "figures_generated",
                    models.BooleanField(
                        default=False, help_text="Visualizations generated"
                    ),
                ),
                (
                    "manuscript_generated",
                    models.BooleanField(
                        default=False, help_text="Manuscript generated"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("collaborator", "Collaborator"),
                            ("viewer", "Viewer"),
                        ],
                        default="collaborator",
                        max_length=20,
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("read", "Read Only"),
                            ("write", "Read/Write"),
                            ("admin", "Full Admin"),
                        ],
                        default="read",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="project_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "user")},
            },
        ),
        migrations.CreateModel(
            name="ResearchGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_app_led_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_groups",
                        to="project_app.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="project_app_collaborative_projects",
                through="project_app.ProjectMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="project_app.organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_app_owned_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="research_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated research group/lab",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="project_app.researchgroup",
            ),
        ),
        migrations.CreateModel(
            name="ProjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("files", "Files"),
                            ("documents", "Documents"),
                            ("code", "Code"),
                            ("data", "Data"),
                            ("settings", "Settings"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_permissions",
                        to="project_app.projectmembership",
                    ),
                ),
            ],
            options={
                "unique_together": {("membership", "resource_type")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("name", "owner")},
        ),
    ]
