# Generated by Django 4.2.11 on 2025-10-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="hypotheses",
            field=models.TextField(
                blank=True, help_text="Research hypotheses (optional)"
            ),
        ),
    ]
