# Generated by Django 4.2.11 on 2025-10-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0002_alter_project_hypotheses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
    ]
