# Generated by Django 4.2.11 on 2025-06-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0001_initial'),
        ('project_app', '0002_generate_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='project', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='manuscript_draft',
            field=models.ForeignKey(blank=True, help_text='Associated manuscript document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_app_manuscripts', to='document_app.document'),
        ),
    ]
