# Generated by Django 5.2.7 on 2025-10-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_app", "0004_alter_project_collaborators"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                help_text="Repository visibility: public (anyone can see) or private (only collaborators)",
                max_length=20,
            ),
        ),
    ]
