# Generated by Django 5.2.7 on 2025-10-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_app", "0005_project_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="git_clone_path",
            field=models.CharField(
                blank=True, help_text="Local git clone path", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="git_url",
            field=models.URLField(blank=True, help_text="Git clone URL (SSH or HTTPS)"),
        ),
        migrations.AddField(
            model_name="project",
            name="gitea_enabled",
            field=models.BooleanField(
                default=False, help_text="Gitea integration enabled"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="gitea_repo_id",
            field=models.IntegerField(
                blank=True, help_text="Gitea repository ID", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="gitea_repo_name",
            field=models.CharField(
                blank=True, help_text="Gitea repository name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="source",
            field=models.CharField(
                choices=[
                    ("scitex", "Created in SciTeX"),
                    ("github", "Imported from GitHub"),
                    ("gitlab", "Imported from GitLab"),
                    ("bitbucket", "Imported from Bitbucket"),
                    ("git", "Cloned from Git URL"),
                ],
                default="scitex",
                help_text="Project source",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="Original source URL (if imported)"
            ),
        ),
    ]
