# Generated by Django 5.2.7 on 2025-10-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0006_project_git_clone_path_project_git_url_and_more"),
    ]

    operations = []
