# Generated by Django 5.2.7 on 2025-10-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0007_remove_hypotheses_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="hypotheses",
        ),
    ]
