# Generated by Django 5.2.7 on 2025-10-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0008_remove_project_hypotheses"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="gitea_clone_url",
            field=models.URLField(blank=True, help_text="Gitea HTTPS clone URL"),
        ),
        migrations.AddField(
            model_name="project",
            name="gitea_repo_url",
            field=models.URLField(blank=True, help_text="Gitea repository web URL"),
        ),
        migrations.AddField(
            model_name="project",
            name="gitea_ssh_url",
            field=models.CharField(
                blank=True, help_text="Gitea SSH clone URL", max_length=500
            ),
        ),
    ]
