# Generated by Django 5.2.7 on 2025-10-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations_app", "0001_initial"),
        ("project_app", "0009_project_gitea_clone_url_project_gitea_repo_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="organizations_app.organization",
            ),
        ),
        migrations.RemoveField(
            model_name="researchgroup",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="researchgroup",
            name="leader",
        ),
        migrations.AlterField(
            model_name="project",
            name="research_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated research group/lab",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="organizations_app.researchgroup",
            ),
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="ResearchGroup",
        ),
    ]
