# Generated by Django 5.2.7 on 2025-10-23 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations_app", "0001_initial"),
        ("project_app", "0010_alter_project_organization_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gitea_enabled", True)),
                fields=("owner", "gitea_repo_name"),
                name="unique_gitea_repo_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gitea_repo_id__isnull", False)),
                fields=("gitea_repo_id",),
                name="unique_gitea_repo_id",
            ),
        ),
    ]
