# Generated by Django 5.2.7 on 2025-10-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0011_add_gitea_uniqueness_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="local_path",
            field=models.CharField(
                blank=True,
                help_text="Path to local project directory (where scitex/.metadata/ lives)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="scitex_project_id",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier linking to scitex/.metadata/ (from scitex.project package)",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
