# Generated by Django 5.2.7 on 2025-10-24 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0012_add_scitex_integration_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time fork was synced with original",
                        null=True,
                    ),
                ),
                (
                    "forked_project",
                    models.ForeignKey(
                        help_text="The new forked project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forked_from",
                        to="project_app.project",
                    ),
                ),
                (
                    "original_project",
                    models.ForeignKey(
                        help_text="The original project that was forked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_forks_set",
                        to="project_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created the fork",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_forks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Fork",
                "verbose_name_plural": "Project Forks",
                "indexes": [
                    models.Index(
                        fields=["user", "original_project"],
                        name="project_app_user_id_a61aa8_idx",
                    ),
                    models.Index(
                        fields=["original_project", "created_at"],
                        name="project_app_origina_c60927_idx",
                    ),
                    models.Index(
                        fields=["forked_project"], name="project_app_forked__fcb547_idx"
                    ),
                ],
                "unique_together": {("user", "original_project", "forked_project")},
            },
        ),
        migrations.CreateModel(
            name="ProjectStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_stars_set",
                        to="project_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_stars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Star",
                "verbose_name_plural": "Project Stars",
                "indexes": [
                    models.Index(
                        fields=["user", "project"],
                        name="project_app_user_id_71d0a1_idx",
                    ),
                    models.Index(
                        fields=["project", "created_at"],
                        name="project_app_project_ddf7e0_idx",
                    ),
                ],
                "unique_together": {("user", "project")},
            },
        ),
        migrations.CreateModel(
            name="ProjectWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_settings",
                    models.CharField(
                        choices=[
                            ("all", "All Activity"),
                            ("participating", "Participating and @mentions"),
                            ("ignoring", "Ignore"),
                        ],
                        default="all",
                        help_text="Notification preference for this project",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_watchers",
                        to="project_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_watches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Watch",
                "verbose_name_plural": "Project Watches",
                "indexes": [
                    models.Index(
                        fields=["user", "project"],
                        name="project_app_user_id_805715_idx",
                    ),
                    models.Index(
                        fields=["project", "created_at"],
                        name="project_app_project_8755fe_idx",
                    ),
                ],
                "unique_together": {("user", "project")},
            },
        ),
    ]
