# Generated by Django 5.2.7 on 2025-10-24 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_app", "0013_projectfork_projectstar_projectwatch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        help_text="PR number (auto-incremented per project)"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="PR title (e.g., 'Add neural decoder model')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="PR description (supports Markdown)"
                    ),
                ),
                (
                    "source_branch",
                    models.CharField(
                        help_text="Branch to merge from (e.g., 'feature/add-decoder')",
                        max_length=255,
                    ),
                ),
                (
                    "target_branch",
                    models.CharField(
                        default="main",
                        help_text="Branch to merge into (e.g., 'main', 'develop')",
                        max_length=255,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("merged", "Merged"),
                            ("draft", "Draft"),
                        ],
                        db_index=True,
                        default="open",
                        help_text="Current state of the PR",
                        max_length=20,
                    ),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a draft PR (work in progress)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "merge_commit_sha",
                    models.CharField(
                        blank=True, help_text="SHA of the merge commit", max_length=40
                    ),
                ),
                (
                    "merge_strategy",
                    models.CharField(
                        blank=True,
                        help_text="Merge strategy used (merge, squash, rebase)",
                        max_length=20,
                    ),
                ),
                (
                    "has_conflicts",
                    models.BooleanField(
                        default=False, help_text="Whether PR has merge conflicts"
                    ),
                ),
                (
                    "conflict_files",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of files with conflicts",
                    ),
                ),
                (
                    "required_approvals",
                    models.IntegerField(
                        default=0, help_text="Number of approvals required before merge"
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="PR labels (e.g., ['bug', 'enhancement'])",
                    ),
                ),
                (
                    "ci_status",
                    models.CharField(
                        blank=True,
                        help_text="CI/CD check status (pending, success, failure)",
                        max_length=20,
                    ),
                ),
                (
                    "assignees",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users assigned to work on this PR",
                        related_name="assigned_prs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created the PR",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_pull_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who merged the PR",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_pull_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this PR belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="project_app.project",
                    ),
                ),
                (
                    "reviewers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users requested to review this PR",
                        related_name="review_requested_prs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pull Request",
                "verbose_name_plural": "Pull Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PullRequestCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commit_hash",
                    models.CharField(help_text="Git commit SHA", max_length=40),
                ),
                ("commit_message", models.TextField(help_text="Commit message")),
                (
                    "author_name",
                    models.CharField(help_text="Git author name", max_length=255),
                ),
                (
                    "author_email",
                    models.CharField(help_text="Git author email", max_length=255),
                ),
                (
                    "committed_at",
                    models.DateTimeField(help_text="Git commit timestamp"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pull_request",
                    models.ForeignKey(
                        help_text="PR this commit belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="project_app.pullrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pull Request Commit",
                "verbose_name_plural": "Pull Request Commits",
                "ordering": ["committed_at"],
            },
        ),
        migrations.CreateModel(
            name="PullRequestEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("opened", "Opened"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                            ("merged", "Merged"),
                            ("reviewed", "Reviewed"),
                            ("comment", "Comment Added"),
                            ("commit", "Commit Added"),
                            ("label", "Label Changed"),
                            ("assignee", "Assignee Changed"),
                            ("reviewer", "Reviewer Changed"),
                        ],
                        help_text="Type of event",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional event metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="User who triggered the event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pr_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pull_request",
                    models.ForeignKey(
                        help_text="PR this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="project_app.pullrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pull Request Event",
                "verbose_name_plural": "Pull Request Events",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PullRequestLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label name (e.g., 'bug', 'enhancement')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#0969da",
                        help_text="Label color (hex code)",
                        max_length=7,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Label description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this label belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pr_labels",
                        to="project_app.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pull Request Label",
                "verbose_name_plural": "Pull Request Labels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PullRequestReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("changes_requested", "Changes Requested"),
                            ("commented", "Commented"),
                        ],
                        help_text="Review state",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Review comments (supports Markdown)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "pull_request",
                    models.ForeignKey(
                        help_text="PR being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="project_app.pullrequest",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="User submitting the review",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pr_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pull Request Review",
                "verbose_name_plural": "Pull Request Reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PullRequestComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Comment content (supports Markdown)"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="File path for inline comments",
                        max_length=500,
                    ),
                ),
                (
                    "line_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Line number for inline comments",
                        null=True,
                    ),
                ),
                (
                    "commit_sha",
                    models.CharField(
                        blank=True,
                        help_text="Commit SHA for inline comments",
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("edited", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who wrote the comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pr_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent comment for threaded discussions",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="project_app.pullrequestcomment",
                    ),
                ),
                (
                    "pull_request",
                    models.ForeignKey(
                        help_text="PR this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="project_app.pullrequest",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        help_text="Review this comment is part of (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="project_app.pullrequestreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pull Request Comment",
                "verbose_name_plural": "Pull Request Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(
                fields=["project", "state"], name="project_app_project_174560_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(
                fields=["project", "number"], name="project_app_project_444fc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(
                fields=["author", "created_at"], name="project_app_author__b9bb3f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pullrequest",
            unique_together={("project", "number")},
        ),
        migrations.AddIndex(
            model_name="pullrequestcommit",
            index=models.Index(
                fields=["pull_request", "committed_at"],
                name="project_app_pull_re_079fa8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequestcommit",
            index=models.Index(
                fields=["commit_hash"], name="project_app_commit__0a1989_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pullrequestcommit",
            unique_together={("pull_request", "commit_hash")},
        ),
        migrations.AddIndex(
            model_name="pullrequestevent",
            index=models.Index(
                fields=["pull_request", "created_at"],
                name="project_app_pull_re_644a81_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequestevent",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="project_app_event_t_a28856_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pullrequestlabel",
            unique_together={("project", "name")},
        ),
        migrations.AddIndex(
            model_name="pullrequestreview",
            index=models.Index(
                fields=["pull_request", "created_at"],
                name="project_app_pull_re_1332dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequestreview",
            index=models.Index(
                fields=["reviewer", "created_at"], name="project_app_reviewe_0b130a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequestcomment",
            index=models.Index(
                fields=["pull_request", "created_at"],
                name="project_app_pull_re_9da631_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequestcomment",
            index=models.Index(
                fields=["author", "created_at"], name="project_app_author__05c70a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequestcomment",
            index=models.Index(
                fields=["file_path", "line_number"],
                name="project_app_file_pa_cc5377_idx",
            ),
        ),
    ]
