# Generated by Django 5.2.7 on 2025-10-24 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_app", "0014_pullrequest_pullrequestcommit_pullrequestevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        help_text="Issue number (auto-incremented per project)"
                    ),
                ),
                ("title", models.CharField(help_text="Issue title", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Issue description (supports Markdown)"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        db_index=True,
                        default="open",
                        help_text="Current state of the issue",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reactions_count",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Reaction counts (e.g., {'thumbsup': 5, 'heart': 2})",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created the issue",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who closed the issue",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this issue belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="project_app.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue",
                "verbose_name_plural": "Issues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="project_app.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Assignment",
                "verbose_name_plural": "Issue Assignments",
                "ordering": ["assigned_at"],
                "unique_together": {("issue", "user")},
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users assigned to this issue",
                related_name="assigned_issues",
                through="project_app.IssueAssignment",
                through_fields=("issue", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="IssueLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label name (e.g., 'bug', 'enhancement')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Label description"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#0366d6",
                        help_text="Label color (hex code, e.g., #0366d6)",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this label belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_labels",
                        to="project_app.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Label",
                "verbose_name_plural": "Issue Labels",
                "ordering": ["name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Labels assigned to this issue",
                related_name="issues",
                to="project_app.issuelabel",
            ),
        ),
        migrations.CreateModel(
            name="IssueMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Milestone title", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Milestone description"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        help_text="Milestone state",
                        max_length=20,
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, help_text="Milestone due date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this milestone belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_milestones",
                        to="project_app.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Milestone",
                "verbose_name_plural": "Issue Milestones",
                "ordering": ["due_date", "title"],
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                help_text="Milestone this issue belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="project_app.issuemilestone",
            ),
        ),
        migrations.CreateModel(
            name="IssueComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Comment content (supports Markdown)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False, help_text="Whether comment has been edited"
                    ),
                ),
                (
                    "reactions_count",
                    models.JSONField(
                        blank=True, default=dict, help_text="Reaction counts"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who wrote the comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        help_text="Issue this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="project_app.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Comment",
                "verbose_name_plural": "Issue Comments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["issue", "created_at"],
                        name="project_app_issue_i_dbea3a_idx",
                    ),
                    models.Index(
                        fields=["author", "created_at"],
                        name="project_app_author__56d747_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IssueEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                            ("assigned", "Assigned"),
                            ("unassigned", "Unassigned"),
                            ("labeled", "Labeled"),
                            ("unlabeled", "Unlabeled"),
                            ("milestoned", "Milestoned"),
                            ("demilestoned", "Demilestoned"),
                            ("referenced", "Referenced"),
                            ("mentioned", "Mentioned"),
                        ],
                        help_text="Type of event",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Event metadata (e.g., label name, assignee username)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "issue",
                    models.ForeignKey(
                        help_text="Issue this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="project_app.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Event",
                "verbose_name_plural": "Issue Events",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["issue", "created_at"],
                        name="project_app_issue_i_0e584b_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="project_app_user_id_580c72_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "state"], name="project_app_project_338950_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "number"], name="project_app_project_dd4a26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["author", "created_at"], name="project_app_author__18e090_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issue",
            unique_together={("project", "number")},
        ),
    ]
