# Generated by Django 5.2.7 on 2025-10-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0016_project_primary_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(default="project", max_length=200),
        ),
    ]
