# Generated by Django 5.2.7 on 2025-11-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_app", "0017_alter_project_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitor_number",
                    models.IntegerField(
                        help_text="Visitor slot number (1-32)", unique=True
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, help_text="Django session key", max_length=255
                    ),
                ),
                (
                    "allocation_token",
                    models.CharField(
                        help_text="Security token", max_length=64, unique=True
                    ),
                ),
                ("allocated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Allocation expiry time"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Active allocation"),
                ),
            ],
            options={
                "ordering": ["visitor_number"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "expires_at"],
                        name="project_app_is_acti_b617ec_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="project_app_session_28a1c2_idx"
                    ),
                    models.Index(
                        fields=["allocation_token"],
                        name="project_app_allocat_db90a7_idx",
                    ),
                ],
            },
        ),
    ]
