# Generated by Django 5.2.7 on 2025-11-16 15:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_app",
            "0020_workflow_workflowrun_workflowjob_workflowartifact_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("name", "owner"), ("owner", "slug")},
        ),
    ]
