# Generated by Django 5.2.7 on 2025-11-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0021_alter_project_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitorallocation",
            name="visitor_number",
            field=models.IntegerField(
                help_text="Visitor slot number (1-4 default, configurable)", unique=True
            ),
        ),
    ]
