# Generated by Django 5.2.7 on 2025-11-26 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0022_alter_visitorallocation_visitor_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("local", "Local Repository"),
                    ("remote", "Remote Filesystem"),
                ],
                default="local",
                help_text="Local (Git-enabled) or Remote (SSH mount, no Git)",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RemoteCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Spartan HPC', 'AWS Server')",
                        max_length=100,
                    ),
                ),
                (
                    "ssh_host",
                    models.CharField(
                        help_text="Hostname or IP address", max_length=255
                    ),
                ),
                ("ssh_port", models.IntegerField(default=22)),
                (
                    "ssh_username",
                    models.CharField(
                        help_text="Username on remote system", max_length=100
                    ),
                ),
                (
                    "ssh_public_key",
                    models.TextField(help_text="SSH public key (RSA, ED25519, etc.)"),
                ),
                (
                    "ssh_key_fingerprint",
                    models.CharField(
                        help_text="SSH key fingerprint for display", max_length=100
                    ),
                ),
                (
                    "private_key_path",
                    models.CharField(
                        help_text="Path to private key file on server", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used_at", "-created_at"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="RemoteProjectConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ssh_host",
                    models.CharField(help_text="Remote hostname", max_length=255),
                ),
                ("ssh_port", models.IntegerField(default=22)),
                (
                    "ssh_username",
                    models.CharField(
                        help_text="Username on remote system", max_length=100
                    ),
                ),
                (
                    "remote_path",
                    models.CharField(
                        help_text="Absolute path on remote system (e.g., /home/username/project)",
                        max_length=500,
                    ),
                ),
                ("is_mounted", models.BooleanField(default=False)),
                (
                    "mount_point",
                    models.CharField(
                        blank=True,
                        help_text="Local mount point (e.g., /tmp/scitex_remote/1/project-slug/)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "mounted_at",
                    models.DateTimeField(
                        blank=True, help_text="When mount was created", null=True
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time remote filesystem was accessed",
                        null=True,
                    ),
                ),
                (
                    "last_test_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last connection test timestamp",
                        null=True,
                    ),
                ),
                (
                    "last_test_success",
                    models.BooleanField(
                        default=False,
                        help_text="Whether last connection test succeeded",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        help_text="Associated project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_config",
                        to="project_app.project",
                    ),
                ),
                (
                    "remote_credential",
                    models.ForeignKey(
                        help_text="SSH key for authentication",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_app.remotecredential",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Project Configuration",
                "verbose_name_plural": "Remote Project Configurations",
            },
        ),
    ]
