# Generated by Django 4.2.11 on 2025-06-29 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Configuration', max_length=100)),
                ('emacs_version', models.CharField(blank=True, max_length=50)),
                ('init_file_path', models.CharField(default='~/.emacs.d/init.el', max_length=255)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('model_version', models.CharField(default='claude-3-opus-20240229', max_length=50)),
                ('max_tokens', models.IntegerField(default=4000)),
                ('temperature', models.FloatField(default=0.7)),
                ('enable_code_completion', models.BooleanField(default=True)),
                ('enable_org_mode_assistance', models.BooleanField(default=True)),
                ('enable_latex_support', models.BooleanField(default=True)),
                ('enable_shell_integration', models.BooleanField(default=True)),
                ('enable_project_awareness', models.BooleanField(default=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('workflow_definition', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('current_step', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('results', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('error', 'Error')], default='active', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('buffer_mode', models.CharField(blank=True, max_length=50)),
                ('project_path', models.CharField(blank=True, max_length=255)),
                ('request_count', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('response_time_avg', models.FloatField(default=0)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine_app.engineconfiguration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EngineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('code_complete', 'Code Completion'), ('analyze_region', 'Analyze Region'), ('help_buffer', 'Help with Buffer'), ('org_assist', 'Org-mode Assistance'), ('latex_help', 'LaTeX Help'), ('shell_command', 'Shell Command'), ('custom', 'Custom Query')], max_length=20)),
                ('prompt', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('response', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('response_time', models.FloatField()),
                ('buffer_name', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('language_mode', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='engine_app.enginesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('jupyter', 'Jupyter Notebook'), ('git', 'Git'), ('docker', 'Docker'), ('conda', 'Conda/Mamba'), ('slurm', 'SLURM'), ('aws', 'AWS'), ('gcp', 'Google Cloud'), ('custom', 'Custom')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('configuration', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['integration_type', 'name'],
                'unique_together': {('user', 'integration_type', 'name')},
            },
        ),
    ]
