"""
README File Generator Module

Handles creation of README files for projects including minimal and comprehensive
versions for empty and templated projects.
"""

from pathlib import Path
import logging

from .config_generator import ConfigGeneratorManager
from ...models import Project

logger = logging.getLogger(__name__)


class ReadmeConfigOperationsManager:
    """Manages README and configuration file creation for projects."""

    def __init__(self, filesystem_manager):
        """
        Initialize ReadmeConfigOperationsManager.

        Args:
            filesystem_manager: Parent ProjectFilesystemManager instance
        """
        self.manager = filesystem_manager
        self.config_gen = ConfigGeneratorManager(filesystem_manager)

    # Delegate config operations
    def create_project_config_files(self, project: Project, project_path: Path):
        """Create essential configuration files for the project."""
        return self.config_gen.create_project_config_files(project, project_path)

    def create_requirements_file(self, project: Project, project_path: Path):
        """Create requirements.txt with essential scientific packages."""
        return self.config_gen.create_requirements_file(project, project_path)

    def create_minimal_readme(self, project: Project, project_path: Path):
        """Create minimal README file for empty projects."""
        readme_content = f"""# {project.name}

**Created:** {project.created_at.strftime("%Y-%m-%d")}
**Owner:** {project.owner.get_full_name() or project.owner.username}

## Description

{project.description or "No description provided."}

## Getting Started

This is an empty project directory. You can:

1. **Create from template** - Click the "Create from template" button to set up a full SciTeX research project structure
2. **Upload your files** - Upload your existing project files through the web interface
3. **Create manually** - Organize your project structure as you prefer

---
*Created with SciTeX Cloud*
"""

        readme_path = project_path / "README.md"
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(readme_content)

    def create_project_readme(self, project: Project, project_path: Path):
        """Create comprehensive README file for the project."""
        readme_content = f"""# {project.name}

**Created:** {project.created_at.strftime("%Y-%m-%d")}
**Owner:** {project.owner.get_full_name() or project.owner.username}
**Progress:** {getattr(project, "progress", 0)}%

## Description

{project.description or "No description provided."}

## Hypotheses

{getattr(project, "hypotheses", "No hypotheses defined.") or "No hypotheses defined."}

## Directory Structure

This project follows the standardized SciTeX research project structure:

- `config/` - Configuration files (YAML, JSON, etc.)
- `data/` - Research data (raw, processed, figures, models)
- `scripts/` - Source code and analysis scripts
- `docs/` - Documentation (manuscripts, notes, references)
- `results/` - Analysis outputs (outputs, reports, analysis)
- `temp/` - Temporary files (cache, logs, tmp)

## Getting Started

This project directory is managed by SciTeX Cloud. You can:

1. Upload files using the web interface
2. Edit documents in the Writer module
3. Run code in the Code module
4. Create visualizations in the Viz module
5. Manage references in the Scholar module

## Project Management

- Project ID: {project.id}
- Created: {project.created_at.strftime("%Y-%m-%d %H:%M:%S")}
- Last Updated: {project.updated_at.strftime("%Y-%m-%d %H:%M:%S")}

---
*This README was automatically generated by SciTeX Cloud*
"""

        readme_path = project_path / "README.md"
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(readme_content)
