# Generated by Django 4.2.11 on 2025-10-15 14:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_app", "0001_initial"),
        ("writer_app", "0001_initial"),
        ("code_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("highlight", "Text Highlight"),
                            ("note", "Margin Note"),
                            ("comment", "General Comment"),
                            ("question", "Question"),
                            ("important", "Important Point"),
                            ("critique", "Critical Analysis"),
                            ("summary", "Summary"),
                            ("methodology", "Methodology Note"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                (
                    "text_content",
                    models.TextField(help_text="The annotation text/note content"),
                ),
                (
                    "highlighted_text",
                    models.TextField(
                        blank=True,
                        help_text="The text that was highlighted (if applicable)",
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True, help_text="Page number in document", null=True
                    ),
                ),
                (
                    "position_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON data for precise positioning",
                    ),
                ),
                (
                    "privacy_level",
                    models.CharField(
                        choices=[
                            ("private", "Private (Only Me)"),
                            ("shared", "Shared with Collaborators"),
                            ("public", "Public (Anyone can view)"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False,
                        help_text="For questions/issues - mark as resolved",
                    ),
                ),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(help_text="Reply content")),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#1a2332", help_text="Hex color code", max_length=7
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("up", "Upvote"), ("down", "Downvote")], max_length=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("orcid", models.CharField(blank=True, db_index=True, max_length=19)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("affiliation", models.CharField(blank=True, max_length=500)),
                ("h_index", models.IntegerField(blank=True, null=True)),
                ("total_citations", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="AuthorPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_order", models.IntegerField(default=1)),
                ("is_corresponding", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["author_order"],
            },
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("citation_context", models.TextField(blank=True)),
                ("section", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CollaborationGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Allow anyone to join"
                    ),
                ),
                (
                    "auto_approve_members",
                    models.BooleanField(
                        default=True, help_text="Auto-approve membership requests"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#1a2332",
                        help_text="Hex color code for collection",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-folder",
                        help_text="FontAwesome icon class",
                        max_length=50,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Allow others to see this collection"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[
                            ("raw_data", "Raw Data"),
                            ("processed_data", "Processed Data"),
                            ("analysis_results", "Analysis Results"),
                            ("code_output", "Code Execution Output"),
                            ("supplementary", "Supplementary Materials"),
                            ("replication_data", "Replication Data"),
                            ("metadata", "Metadata Only"),
                        ],
                        max_length=30,
                    ),
                ),
                ("keywords", models.CharField(blank=True, max_length=500)),
                ("repository_id", models.CharField(blank=True, max_length=200)),
                ("repository_url", models.URLField(blank=True)),
                ("repository_doi", models.CharField(blank=True, max_length=100)),
                ("version", models.CharField(default="1.0", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("published", "Published"),
                            ("updated", "Updated"),
                            ("deprecated", "Deprecated"),
                            ("deleted", "Deleted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("restricted", "Restricted Access"),
                            ("embargoed", "Embargoed"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("file_count", models.IntegerField(default=0)),
                ("total_size_bytes", models.BigIntegerField(default=0)),
                ("file_formats", models.JSONField(default=list)),
                ("license", models.CharField(blank=True, max_length=200)),
                ("access_conditions", models.TextField(blank=True)),
                ("embargo_until", models.DateTimeField(blank=True, null=True)),
                ("download_count", models.IntegerField(default=0)),
                ("citation_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DatasetFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=500)),
                ("file_path", models.CharField(blank=True, max_length=1000)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("data", "Data File"),
                            ("code", "Code File"),
                            ("documentation", "Documentation"),
                            ("metadata", "Metadata"),
                            ("readme", "README"),
                            ("license", "License"),
                            ("figure", "Figure/Image"),
                            ("supplementary", "Supplementary"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_format", models.CharField(blank=True, max_length=50)),
                ("size_bytes", models.BigIntegerField()),
                ("checksum_md5", models.CharField(blank=True, max_length=32)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("mime_type", models.CharField(blank=True, max_length=200)),
                ("repository_file_id", models.CharField(blank=True, max_length=200)),
                ("download_url", models.URLField(blank=True)),
                ("preview_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("encoding", models.CharField(blank=True, max_length=50)),
                (
                    "local_file",
                    models.FileField(blank=True, null=True, upload_to="dataset_files/"),
                ),
                ("download_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["file_path", "filename"],
            },
        ),
        migrations.CreateModel(
            name="DatasetVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.CharField(max_length=50)),
                ("version_description", models.TextField(blank=True)),
                ("is_current", models.BooleanField(default=False)),
                ("repository_version_id", models.CharField(blank=True, max_length=200)),
                ("repository_version_url", models.URLField(blank=True)),
                ("version_doi", models.CharField(blank=True, max_length=100)),
                ("changes_summary", models.TextField(blank=True)),
                ("files_added", models.IntegerField(default=0)),
                ("files_modified", models.IntegerField(default=0)),
                ("files_deleted", models.IntegerField(default=0)),
                ("metadata_snapshot", models.JSONField(default=dict)),
                ("file_listing", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("invited", "Invited"),
                            ("requested", "Requested"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("abbreviation", models.CharField(blank=True, max_length=100)),
                ("issn", models.CharField(blank=True, db_index=True, max_length=9)),
                ("eissn", models.CharField(blank=True, max_length=9)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                (
                    "impact_factor",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("open_access", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LibraryExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("bibtex", "BibTeX"),
                            ("endnote", "EndNote"),
                            ("ris", "RIS"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("pdf_bundle", "PDF Bundle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("paper_count", models.IntegerField()),
                (
                    "collection_name",
                    models.CharField(
                        blank=True,
                        help_text="Collection name if exported",
                        max_length=200,
                    ),
                ),
                (
                    "filter_criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Applied filters during export",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("similar", "Similar Papers"),
                            ("author_based", "Based on Author"),
                            ("citation_based", "Based on Citations"),
                            ("topic_based", "Based on Topics"),
                            ("collaborative", "Collaborative Filtering"),
                            ("trending", "Trending Papers"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("clicked", models.BooleanField(default=False)),
                (
                    "feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("feedback_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("interacted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "repository_type",
                    models.CharField(
                        choices=[
                            ("zenodo", "Zenodo"),
                            ("figshare", "Figshare"),
                            ("dryad", "Dryad"),
                            ("harvard_dataverse", "Harvard Dataverse"),
                            ("osf", "Open Science Framework"),
                            ("mendeley_data", "Mendeley Data"),
                            ("institutional", "Institutional Repository"),
                            ("custom", "Custom Repository"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("api_base_url", models.URLField()),
                ("api_version", models.CharField(default="v1", max_length=20)),
                ("api_documentation_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("supports_doi", models.BooleanField(default=True)),
                ("supports_versioning", models.BooleanField(default=True)),
                ("supports_private_datasets", models.BooleanField(default=True)),
                ("max_file_size_mb", models.IntegerField(default=50000)),
                ("max_dataset_size_mb", models.IntegerField(default=50000)),
                ("requires_authentication", models.BooleanField(default=True)),
                ("supports_metadata_formats", models.JSONField(default=list)),
                ("supported_file_formats", models.JSONField(default=list)),
                ("license_options", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Under Maintenance"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_open_access", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("total_deposits", models.IntegerField(default=0)),
                ("active_connections", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RepositoryConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("api_token", models.CharField(blank=True, max_length=500)),
                ("api_secret", models.CharField(blank=True, max_length=500)),
                ("oauth_token", models.CharField(blank=True, max_length=500)),
                ("oauth_refresh_token", models.CharField(blank=True, max_length=500)),
                ("username", models.CharField(blank=True, max_length=200)),
                (
                    "connection_name",
                    models.CharField(
                        help_text="User-defined name for this connection",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("invalid", "Invalid"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending Verification"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_verified", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("auto_sync_enabled", models.BooleanField(default=True)),
                ("notification_enabled", models.BooleanField(default=True)),
                ("total_deposits", models.IntegerField(default=0)),
                ("total_downloads", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("error_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_connections",
                        to="scholar_app.repository",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchFilter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("date_range", "Date Range"),
                            ("author", "Author"),
                            ("journal", "Journal"),
                            ("topic", "Topic"),
                            ("citation_count", "Citation Count"),
                            ("document_type", "Document Type"),
                            ("open_access", "Open Access"),
                            ("language", "Language"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("configuration", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["filter_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField(db_index=True)),
                ("abstract", models.TextField(blank=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("article", "Journal Article"),
                            ("preprint", "Preprint"),
                            ("book", "Book"),
                            ("chapter", "Book Chapter"),
                            ("conference", "Conference Paper"),
                            ("thesis", "Thesis/Dissertation"),
                            ("report", "Technical Report"),
                            ("dataset", "Dataset"),
                        ],
                        default="article",
                        max_length=20,
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "pmid",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True, unique=True
                    ),
                ),
                (
                    "arxiv_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True, unique=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pubmed", "PubMed"),
                            ("arxiv", "arXiv"),
                            ("doi", "DOI"),
                            ("google_scholar", "Google Scholar"),
                            ("internal", "Internal"),
                            ("manual", "Manual Entry"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("full_text", models.TextField(blank=True)),
                ("pdf_url", models.URLField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="scholar/pdfs/"),
                ),
                (
                    "bibtex_file",
                    models.FileField(
                        blank=True, null=True, upload_to="scholar/bibtex/"
                    ),
                ),
                (
                    "bibtex_content",
                    models.TextField(blank=True, help_text="BibTeX citation content"),
                ),
                ("keywords", models.TextField(blank=True)),
                ("citation_count", models.IntegerField(default=0)),
                (
                    "citation_source",
                    models.CharField(
                        blank=True,
                        help_text="Source of citation data (semantic_scholar, crossref, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "citation_last_updated",
                    models.DateTimeField(
                        blank=True,
                        help_text="When citation count was last updated",
                        null=True,
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("download_count", models.IntegerField(default=0)),
                ("relevance_score", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("retracted", "Retracted"),
                            ("pending", "Pending Review"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_open_access", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        through="scholar_app.AuthorPaper", to="scholar_app.author"
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scholar_app.journal",
                    ),
                ),
            ],
            options={
                "ordering": ["-publication_date", "-relevance_score"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.TextField()),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("simple", "Simple Search"),
                            ("advanced", "Advanced Search"),
                            ("author", "Author Search"),
                            ("citation", "Citation Search"),
                            ("semantic", "Semantic Search"),
                        ],
                        default="simple",
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("result_count", models.IntegerField(default=0)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_sources",
                    models.JSONField(
                        default=dict,
                        help_text="Dictionary of source preferences: {'pubmed': True, 'arxiv': True, etc.}",
                    ),
                ),
                (
                    "default_sort_by",
                    models.CharField(
                        choices=[
                            ("relevance", "Most Relevant"),
                            ("date", "Most Recent"),
                            ("citations", "Most Cited"),
                        ],
                        default="relevance",
                        max_length=20,
                    ),
                ),
                (
                    "default_filters",
                    models.JSONField(
                        default=dict,
                        help_text="Default filter settings: {'open_access': False, 'recent_only': False, etc.}",
                    ),
                ),
                (
                    "results_per_page",
                    models.IntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("show_abstracts", models.BooleanField(default=True)),
                ("show_preview_images", models.BooleanField(default=True)),
                ("auto_save_searches", models.BooleanField(default=True)),
                ("email_search_alerts", models.BooleanField(default=False)),
                (
                    "pubmed_api_key",
                    models.TextField(
                        blank=True, help_text="Encrypted NCBI API key for PubMed"
                    ),
                ),
                (
                    "google_scholar_api_key",
                    models.TextField(
                        blank=True, help_text="Encrypted Google Scholar API key"
                    ),
                ),
                (
                    "semantic_scholar_api_key",
                    models.TextField(
                        blank=True, help_text="Encrypted Semantic Scholar API key"
                    ),
                ),
                (
                    "crossref_api_key",
                    models.TextField(
                        blank=True, help_text="Encrypted Crossref API key"
                    ),
                ),
                (
                    "unpaywall_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email for Unpaywall API compliance",
                        max_length=254,
                    ),
                ),
                (
                    "api_usage_count",
                    models.JSONField(
                        default=dict,
                        help_text="Track API usage by source: {'pubmed': 150, 'arxiv': 75, etc.}",
                    ),
                ),
                (
                    "api_rate_limit_reset",
                    models.JSONField(
                        default=dict, help_text="Track rate limit reset times by source"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholar_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
            },
        ),
        migrations.CreateModel(
            name="UserLibrary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "personal_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="user_library/pdfs/"
                    ),
                ),
                (
                    "personal_bibtex",
                    models.FileField(
                        blank=True, null=True, upload_to="user_library/bibtex/"
                    ),
                ),
                (
                    "personal_notes",
                    models.TextField(
                        blank=True, help_text="Personal notes about this paper"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Personal tags, comma-separated",
                        max_length=500,
                    ),
                ),
                (
                    "reading_status",
                    models.CharField(
                        choices=[
                            ("to_read", "To Read"),
                            ("reading", "Currently Reading"),
                            ("read", "Completed"),
                            ("referenced", "For Reference"),
                            ("favorite", "Favorite"),
                        ],
                        default="to_read",
                        max_length=20,
                    ),
                ),
                (
                    "importance_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "exported_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this paper was exported"
                    ),
                ),
                ("last_exported", models.DateTimeField(blank=True, null=True)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="library_papers",
                        to="scholar_app.collection",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="scholar_app.searchindex",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated research project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_papers",
                        to="project_app.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("paper_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="scholar_app.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rank", models.IntegerField()),
                ("score", models.FloatField()),
                ("snippet", models.TextField(blank=True)),
                ("clicked", models.BooleanField(default=False)),
                ("click_timestamp", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scholar_app.searchindex",
                    ),
                ),
                (
                    "search_query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="scholar_app.searchquery",
                    ),
                ),
            ],
            options={
                "ordering": ["search_query", "rank"],
            },
        ),
        migrations.AddField(
            model_name="searchindex",
            name="topics",
            field=models.ManyToManyField(blank=True, to="scholar_app.topic"),
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("query_text", models.TextField()),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("simple", "Simple Search"),
                            ("advanced", "Advanced Search"),
                            ("author", "Author Search"),
                            ("citation", "Citation Search"),
                            ("semantic", "Semantic Search"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("email_alerts", models.BooleanField(default=False)),
                (
                    "alert_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("never", "Never"),
                        ],
                        default="never",
                        max_length=10,
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RepositorySync",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload to Repository"),
                            ("download", "Download from Repository"),
                            ("metadata_update", "Update Metadata"),
                            ("status_check", "Status Check"),
                            ("full_sync", "Full Synchronization"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_items", models.IntegerField(default=0)),
                ("completed_items", models.IntegerField(default=0)),
                ("failed_items", models.IntegerField(default=0)),
                ("total_bytes", models.BigIntegerField(default=0)),
                ("transferred_bytes", models.BigIntegerField(default=0)),
                ("result_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("sync_log", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_completion", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syncs",
                        to="scholar_app.dataset",
                    ),
                ),
                (
                    "repository_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syncs",
                        to="scholar_app.repositoryconnection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository_syncs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["repository_type", "status"],
                name="scholar_app_reposit_aa346d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["is_default"], name="scholar_app_is_defa_d46050_idx"
            ),
        ),
        migrations.AddField(
            model_name="recommendationlog",
            name="recommended_paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommended_as",
                to="scholar_app.searchindex",
            ),
        ),
        migrations.AddField(
            model_name="recommendationlog",
            name="source_paper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation_source",
                to="scholar_app.searchindex",
            ),
        ),
        migrations.AddField(
            model_name="recommendationlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="libraryexport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library_exports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(fields=["issn"], name="scholar_app_issn_44674a_idx"),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scholar_app.collaborationgroup",
            ),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="datasetversion",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="scholar_app.dataset",
            ),
        ),
        migrations.AddField(
            model_name="datasetversion",
            name="parent_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_versions",
                to="scholar_app.datasetversion",
            ),
        ),
        migrations.AddField(
            model_name="datasetfile",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="scholar_app.dataset",
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="associated_notebooks",
            field=models.ManyToManyField(
                blank=True, related_name="associated_datasets", to="code_app.notebook"
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="cited_in_manuscripts",
            field=models.ManyToManyField(
                blank=True, related_name="cited_datasets", to="writer_app.manuscript"
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, related_name="shared_datasets", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="generated_by_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_datasets",
                to="code_app.codeexecutionjob",
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_datasets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datasets",
                to="project_app.project",
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="related_papers",
            field=models.ManyToManyField(
                blank=True,
                related_name="associated_datasets",
                to="scholar_app.searchindex",
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="repository_connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datasets",
                to="scholar_app.repositoryconnection",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated research project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collections",
                to="project_app.project",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collaborationgroup",
            name="members",
            field=models.ManyToManyField(
                related_name="collaboration_groups",
                through="scholar_app.GroupMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collaborationgroup",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="cited_paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citations_received",
                to="scholar_app.searchindex",
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="citing_paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citations_made",
                to="scholar_app.searchindex",
            ),
        ),
        migrations.AddField(
            model_name="authorpaper",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scholar_app.author"
            ),
        ),
        migrations.AddField(
            model_name="authorpaper",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scholar_app.searchindex",
            ),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="scholar_app_last_na_45829f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["orcid"], name="scholar_app_orcid_03e223_idx"),
        ),
        migrations.AddField(
            model_name="annotationvote",
            name="annotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="scholar_app.annotation",
            ),
        ),
        migrations.AddField(
            model_name="annotationvote",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="scholar_app.annotationreply",
            ),
        ),
        migrations.AddField(
            model_name="annotationvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="annotationtag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="annotationreply",
            name="annotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="scholar_app.annotation",
            ),
        ),
        migrations.AddField(
            model_name="annotationreply",
            name="parent_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nested_replies",
                to="scholar_app.annotationreply",
            ),
        ),
        migrations.AddField(
            model_name="annotationreply",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_replies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="scholar_app.searchindex",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="annotations", to="scholar_app.annotationtag"
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userlibrary",
            index=models.Index(
                fields=["user", "-saved_at"], name="scholar_app_user_id_6936b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlibrary",
            index=models.Index(
                fields=["project"], name="scholar_app_project_f43a70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlibrary",
            index=models.Index(
                fields=["reading_status"], name="scholar_app_reading_0801bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlibrary",
            index=models.Index(
                fields=["importance_rating"], name="scholar_app_importa_ed698a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userlibrary",
            unique_together={("user", "paper")},
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["name"], name="scholar_app_name_8cff63_idx"),
        ),
        migrations.AddIndex(
            model_name="searchresult",
            index=models.Index(
                fields=["search_query", "rank"], name="scholar_app_search__928744_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["-created_at"], name="scholar_app_created_20203d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["user", "-created_at"], name="scholar_app_user_id_d693e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchindex",
            index=models.Index(
                fields=["publication_date", "relevance_score"],
                name="scholar_app_publica_bb6551_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="searchindex",
            index=models.Index(fields=["doi"], name="scholar_app_doi_25ab66_idx"),
        ),
        migrations.AddIndex(
            model_name="searchindex",
            index=models.Index(fields=["pmid"], name="scholar_app_pmid_ebd9ea_idx"),
        ),
        migrations.AddIndex(
            model_name="searchindex",
            index=models.Index(
                fields=["arxiv_id"], name="scholar_app_arxiv_i_13d7d4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedsearch",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="repositorysync",
            index=models.Index(
                fields=["user", "status"], name="scholar_app_user_id_b8fa54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repositorysync",
            index=models.Index(
                fields=["repository_connection", "sync_type"],
                name="scholar_app_reposit_cc49c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="repositorysync",
            index=models.Index(
                fields=["-created_at"], name="scholar_app_created_21c480_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repositoryconnection",
            index=models.Index(
                fields=["user", "status"], name="scholar_app_user_id_38e473_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repositoryconnection",
            index=models.Index(
                fields=["repository", "status"], name="scholar_app_reposit_a2938e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="repositoryconnection",
            unique_together={("user", "repository", "connection_name")},
        ),
        migrations.AddIndex(
            model_name="recommendationlog",
            index=models.Index(
                fields=["user", "-created_at"], name="scholar_app_user_id_ecaa40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationlog",
            index=models.Index(
                fields=["recommendation_type", "-score"],
                name="scholar_app_recomme_1126e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="libraryexport",
            index=models.Index(
                fields=["user", "-created_at"], name="scholar_app_user_id_96baeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="libraryexport",
            index=models.Index(
                fields=["export_format"], name="scholar_app_export__eddd79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(
                fields=["user", "status"], name="scholar_app_user_id_adedab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(
                fields=["group", "role"], name="scholar_app_group_i_7e8de0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupmembership",
            unique_together={("user", "group")},
        ),
        migrations.AddIndex(
            model_name="datasetversion",
            index=models.Index(
                fields=["dataset", "is_current"], name="scholar_app_dataset_9e149d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetversion",
            index=models.Index(
                fields=["-created_at"], name="scholar_app_created_7d1692_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datasetversion",
            unique_together={("dataset", "version_number")},
        ),
        migrations.AddIndex(
            model_name="datasetfile",
            index=models.Index(
                fields=["dataset", "file_type"], name="scholar_app_dataset_72b8cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetfile",
            index=models.Index(
                fields=["file_format"], name="scholar_app_file_fo_aeccdb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datasetfile",
            unique_together={("dataset", "file_path", "filename")},
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["owner", "status"], name="scholar_app_owner_i_b01bb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["repository_connection", "status"],
                name="scholar_app_reposit_3d97a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["dataset_type"], name="scholar_app_dataset_c85ead_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["visibility"], name="scholar_app_visibil_6ed702_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["-published_at"], name="scholar_app_publish_2aa854_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["user", "name"], name="scholar_app_user_id_023840_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="collaborationgroup",
            index=models.Index(fields=["owner"], name="scholar_app_owner_i_b94d8a_idx"),
        ),
        migrations.AddIndex(
            model_name="collaborationgroup",
            index=models.Index(
                fields=["is_public"], name="scholar_app_is_publ_a70b6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="citation",
            index=models.Index(
                fields=["citing_paper", "cited_paper"],
                name="scholar_app_citing__dfc8d0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="citation",
            unique_together={("citing_paper", "cited_paper")},
        ),
        migrations.AlterUniqueTogether(
            name="authorpaper",
            unique_together={("author", "paper")},
        ),
        migrations.AddIndex(
            model_name="annotationvote",
            index=models.Index(
                fields=["user", "annotation"], name="scholar_app_user_id_d19197_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annotationvote",
            index=models.Index(
                fields=["user", "reply"], name="scholar_app_user_id_d3324c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="annotationvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("annotation__isnull", False)),
                fields=("user", "annotation"),
                name="unique_user_annotation_vote",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotationvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reply__isnull", False)),
                fields=("user", "reply"),
                name="unique_user_reply_vote",
            ),
        ),
        migrations.AddIndex(
            model_name="annotationtag",
            index=models.Index(fields=["name"], name="scholar_app_name_e549da_idx"),
        ),
        migrations.AddIndex(
            model_name="annotationtag",
            index=models.Index(
                fields=["-usage_count"], name="scholar_app_usage_c_7274c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annotationreply",
            index=models.Index(
                fields=["annotation", "created_at"],
                name="scholar_app_annotat_59ee13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["paper", "-created_at"], name="scholar_app_paper_i_a16e7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["user", "-created_at"], name="scholar_app_user_id_ff428c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["annotation_type"], name="scholar_app_annotat_dc0264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["privacy_level"], name="scholar_app_privacy_c738e8_idx"
            ),
        ),
    ]
