# Generated by Django 4.2.11 on 2025-10-15 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scholar_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BibTeXEnrichmentJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("input_file", models.FileField(upload_to="bibtex_uploads/%Y/%m/%d/")),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional project name for organization",
                        max_length=200,
                    ),
                ),
                (
                    "num_workers",
                    models.IntegerField(
                        default=4, help_text="Number of parallel workers"
                    ),
                ),
                (
                    "browser_mode",
                    models.CharField(
                        choices=[
                            ("stealth", "Stealth Mode"),
                            ("interactive", "Interactive Mode"),
                        ],
                        default="stealth",
                        max_length=20,
                    ),
                ),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to="bibtex_enriched/%Y/%m/%d/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_papers", models.IntegerField(default=0)),
                ("processed_papers", models.IntegerField(default=0)),
                ("failed_papers", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "enrichment_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of enrichments: citations added, IFs found, PDFs downloaded, etc.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bibtex_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="scholar_app_user_id_25ccb8_idx",
                    ),
                    models.Index(
                        fields=["status"], name="scholar_app_status_a9b562_idx"
                    ),
                ],
            },
        ),
    ]
