# Generated by Django 4.2.11 on 2025-06-29 15:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_sources', models.JSONField(default=dict, help_text="Dictionary of source preferences: {'pubmed': True, 'arxiv': True, etc.}")),
                ('default_sort_by', models.CharField(choices=[('relevance', 'Most Relevant'), ('date', 'Most Recent'), ('citations', 'Most Cited')], default='relevance', max_length=20)),
                ('default_filters', models.JSONField(default=dict, help_text="Default filter settings: {'open_access': False, 'recent_only': False, etc.}")),
                ('results_per_page', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('show_abstracts', models.BooleanField(default=True)),
                ('show_preview_images', models.BooleanField(default=True)),
                ('auto_save_searches', models.BooleanField(default=True)),
                ('email_search_alerts', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholar_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
