# Generated by Django 5.2.7 on 2025-10-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_app", "0009_project_gitea_clone_url_project_gitea_repo_url_and_more"),
        ("scholar_app", "0002_bibtexenrichmentjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibtexenrichmentjob",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated project for Gitea integration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bibtex_jobs",
                to="project_app.project",
            ),
        ),
    ]
