# Generated by Django 5.2.7 on 2025-10-20 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholar_app", "0002_bibtexenrichmentjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bibtexenrichmentjob",
            name="session_key",
            field=models.CharField(
                blank=True, help_text="For visitor users", max_length=40, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bibtexenrichmentjob",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bibtex_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="bibtexenrichmentjob",
            index=models.Index(
                fields=["session_key", "-created_at"],
                name="scholar_app_session_674c32_idx",
            ),
        ),
    ]
