# Generated by Django 4.2.11 on 2025-06-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_app', '0002_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='api_rate_limit_reset',
            field=models.JSONField(default=dict, help_text='Track rate limit reset times by source'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='api_usage_count',
            field=models.JSONField(default=dict, help_text="Track API usage by source: {'pubmed': 150, 'arxiv': 75, etc.}"),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='crossref_api_key',
            field=models.TextField(blank=True, help_text='Encrypted Crossref API key'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='google_scholar_api_key',
            field=models.TextField(blank=True, help_text='Encrypted Google Scholar API key'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='pubmed_api_key',
            field=models.TextField(blank=True, help_text='Encrypted NCBI API key for PubMed'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='semantic_scholar_api_key',
            field=models.TextField(blank=True, help_text='Encrypted Semantic Scholar API key'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='unpaywall_email',
            field=models.EmailField(blank=True, help_text='Email for Unpaywall API compliance', max_length=254),
        ),
    ]
