# Generated by Django 4.2.11 on 2025-06-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
        ('scholar_app', '0003_userpreference_api_rate_limit_reset_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userlibrary',
            new_name='scholar_app_project_f43a70_idx',
            old_name='scholar_app_project_4438cd_idx',
        ),
        migrations.AddField(
            model_name='collection',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Associated research project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='project_app.project'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='project_app.project'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Associated research project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_papers', to='project_app.project'),
        ),
    ]
