# Generated by Django 5.2.7 on 2025-10-20 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholar_app", "0003_add_project_to_bibtex_job"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibtexenrichmentjob",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this job (null for visitor users)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bibtex_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
