# Generated by Django 5.2.7 on 2025-10-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_app", "0003_add_anonymous_support_to_bibtex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibtexenrichmentjob",
            name="project_name",
            field=models.CharField(
                blank=True,
                help_text="Optional project name for organization",
                max_length=200,
                null=True,
            ),
        ),
    ]
