# Generated by Django 4.2.11 on 2025-06-29 18:42

from django.db import migrations, models
import django.db.models.deletion


def check_and_add_project_field(apps, schema_editor):
    """Safely add project field only if it doesn't exist"""
    db_alias = schema_editor.connection.alias
    
    # Check if the table exists first
    with schema_editor.connection.cursor() as cursor:
        # For SQLite, check if table exists
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name='scholar_app_collection'
        """)
        table_exists = cursor.fetchone()
        
        if not table_exists:
            # Table doesn't exist yet, skip this migration
            return
            
        # Check if project_id column already exists
        cursor.execute("PRAGMA table_info(scholar_app_collection)")
        columns = [row[1] for row in cursor.fetchall()]
        
        if 'project_id' not in columns:
            # Only add the field if it doesn't exist
            Collection = apps.get_model('scholar_app', 'Collection')
            field = models.ForeignKey(
                'project_app.Project', 
                on_delete=models.SET_NULL, 
                null=True, 
                blank=True, 
                related_name='collections', 
                help_text="Associated research project"
            )
            schema_editor.add_field(Collection, field)


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
        ('scholar_app', '0004_rename_scholar_app_project_4438cd_idx_scholar_app_project_f43a70_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(check_and_add_project_field, migrations.RunPython.noop),
    ]
