# Generated by Django 5.2.7 on 2025-10-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholar_app", "0005_alter_bibtexenrichmentjob_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibtexenrichmentjob",
            name="processing_log",
            field=models.TextField(
                blank=True, help_text="Real-time processing log output"
            ),
        ),
    ]
