# Generated by Django 5.2.7 on 2025-10-22 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_app", "0004_allow_null_project_name"),
        ("scholar_app", "0006_bibtexenrichmentjob_processing_log"),
    ]

    operations = []
