# Generated by Django 5.2.7 on 2025-10-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholar_app", "0007_merge_20251022_0114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibtexenrichmentjob",
            name="processing_log",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Real-time processing log for user feedback",
            ),
        ),
    ]
