# Generated by Django 5.2.7 on 2025-10-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholar_app", "0008_alter_bibtexenrichmentjob_processing_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibtexenrichmentjob",
            name="original_filename",
            field=models.CharField(
                blank=True,
                help_text="Original uploaded filename (before Django adds suffix)",
                max_length=255,
            ),
        ),
    ]
