# Generated by Django 5.2.7 on 2025-10-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholar_app", "0009_bibtexenrichmentjob_original_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchindex",
            name="source_engines",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of search engines that found this paper (e.g., ['PubMed', 'CrossRef'])",
            ),
        ),
    ]
