# Generated by Django 5.2.7 on 2025-10-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_app", "0010_searchindex_source_engines"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bibtexenrichmentjob",
            name="original_filename",
        ),
        migrations.RemoveField(
            model_name="bibtexenrichmentjob",
            name="processing_log",
        ),
    ]
