# Generated by Django 5.2.7 on 2025-10-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholar_app", "0011_remove_bibtexenrichmentjob_original_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibtexenrichmentjob",
            name="original_filename",
            field=models.CharField(
                blank=True,
                help_text="Original filename before upload",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bibtexenrichmentjob",
            name="processing_log",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Real-time processing log shown to user",
            ),
        ),
    ]
