# Generated by Django 5.2.7 on 2025-10-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholar_app", "0012_bibtexenrichmentjob_original_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibtexenrichmentjob",
            name="use_cache",
            field=models.BooleanField(
                default=True, help_text="Use cached metadata if available"
            ),
        ),
    ]
