# Generated by Django 5.2.7 on 2025-10-25 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_app", "0005_merge_20251020_1112"),
        ("scholar_app", "0013_bibtexenrichmentjob_use_cache"),
    ]

    operations = []
