# Generated by Django 5.2.7 on 2025-11-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_app", "0014_merge_20251025_0325"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibtexenrichmentjob",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 hash of input file content for deduplication",
                max_length=64,
                null=True,
            ),
        ),
    ]
