# Generated by Django 4.2.11 on 2025-06-29 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('document_type', models.CharField(choices=[('hypothesis', 'Hypothesis'), ('literature_review', 'Literature Review'), ('methodology', 'Methodology'), ('results', 'Results'), ('manuscript', 'Manuscript'), ('revision', 'Revision'), ('note', 'General Note'), ('draft', 'Draft')], default='note', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('file_location', models.CharField(blank=True, help_text='Relative path to file in user directory', max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash for file integrity', max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_app_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='project_app.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
